import assert from 'node:assert/strict'
import { applyKeyword, clampRailWidth, defaultDetailView, emptySelection, initialDetailState, parseDetailView, productBranchDrawerQuery, RAIL_DEFAULT_WIDTH, selectDimension, sumProductPage } from './logic'
import { normalizeSalesDetailRow, sectionQuery, type SalesDetailQuery } from './reportService'

const selected = { ...emptySelection, branch: 'OR', supplier: 'HB215', product: 'P1', page: 3 }
assert.deepEqual(selectDimension(selected, 'supplier', 'HB246'), { ...selected, supplier: 'HB246', page: 1 })
assert.equal(selectDimension(selected, 'branch', 'OR').branch, undefined)
assert.equal(selectDimension(selected, 'product', 'P2').page, 3)
assert.equal(applyKeyword(selected, ' 玛索   pen ').product, undefined)
assert.equal(applyKeyword(selected, ' 玛索   pen ').keyword, '玛索 pen')
const query: SalesDetailQuery = { kind: 'china', startDate: '2026-09-01', endDate: '2026-09-06', compareMode: 'ByWeek',
  compareStartDate: '2025-09-02', compareEndDate: '2025-09-07', branchCodes: ['OR', 'S2'],
  selectedBranchCode: 'OR', selectedSupplierCode: 'HB215', selectedProductCode: 'P1', search: '玛索 pen', pageIndex: 3, pageSize: 20 }
const drawerQuery = productBranchDrawerQuery(query, 'P9')
assert.equal(drawerQuery.selectedProductCode, 'P9', '抽屉查询必须固定点击商品')
assert.equal(drawerQuery.selectedBranchCode, undefined, '抽屉查询不得继承主页面分店筛选')
assert.equal(drawerQuery.search, undefined, '抽屉查询不得继承主页面关键字')
assert.equal(drawerQuery.selectedSupplierCode, 'HB215', '抽屉查询必须保留当前供应商筛选')
assert.deepEqual(drawerQuery.branchCodes, query.branchCodes, '抽屉查询必须保留账号可见分店范围')
assert.equal(drawerQuery.compareStartDate, query.compareStartDate)
assert.equal(drawerQuery.compareEndDate, query.compareEndDate)
assert.equal(drawerQuery.kind, 'china')
assert.equal(query.selectedBranchCode, 'OR', '打开抽屉不得修改主页面筛选和分页')
assert.equal(query.selectedProductCode, 'P1')
assert.equal(query.search, '玛索 pen')
assert.equal(query.pageIndex, 3)
assert.equal(sectionQuery('suppliers', query).selectedSupplierCode, undefined)
assert.equal(sectionQuery('suppliers', query).selectedBranchCode, 'OR')
assert.equal(sectionQuery('suppliers', query).selectedProductCode, 'P1')
assert.equal(sectionQuery('suppliers', query).search, undefined)
assert.equal(sectionQuery('branches', query).selectedBranchCode, undefined)
assert.equal(sectionQuery('products', query).selectedProductCode, undefined)
assert.equal(sectionQuery('summary', query).selectedProductCode, 'P1')
assert.equal(sectionQuery('summary', query).pageIndex, undefined)
const row = normalizeSalesDetailRow({ Code: 'P1', Name: 'Pen', Revenue: 40, GrossProfit: 0, GrossMarginRate: 0, CompareGrossProfit: null })
assert.equal(row.grossProfit, 0)
assert.equal(row.compareGrossProfit, null)
assert.equal(row.orderCount, null, '不可用客单数不能伪装成0')
const summary = sumProductPage([row, normalizeSalesDetailRow({ revenue: 60, grossProfit: 30 })])
assert.equal(summary.grossMarginRate, 0.3, '汇总毛利率加权计算，不平均各行比率')
assert.equal(sumProductPage([row, normalizeSalesDetailRow({ revenue: 60 })]).grossProfit, null)
const pageTotals = sumProductPage([normalizeSalesDetailRow({ revenue: 40, quantity: 8, compareRevenue: 30, compareQuantity: 10 }),
  normalizeSalesDetailRow({ revenue: 60, quantity: 12, compareRevenue: 20, compareQuantity: 0 })])
assert.equal(pageTotals.quantity, 20, '本页合计数量按行累加')
assert.equal(pageTotals.averageUnitPrice, 5, '本页均价 = 合计营业额 ÷ 合计数量，不平均各行均价')
assert.equal(pageTotals.compareAverageUnitPrice, 5)
assert.equal(sumProductPage([normalizeSalesDetailRow({ revenue: 10, quantity: -1 })]).averageUnitPrice, null, '数量 ≤ 0 时不给均价')
assert.equal(sumProductPage([normalizeSalesDetailRow({ revenue: 10, quantity: 1 })]).compareAverageUnitPrice, null, '同期数量缺失时同期均价为空')
assert.equal(clampRailWidth(80), 46, '左栏最宽不超过 46%，商品明细保持主视图')
assert.equal(clampRailWidth(5), 20)
assert.equal(clampRailWidth(RAIL_DEFAULT_WIDTH), RAIL_DEFAULT_WIDTH)
assert.deepEqual(parseDetailView(null), defaultDetailView)
assert.deepEqual(parseDetailView('{"compareView":"side","railCollapsed":true}'), { compareView: 'side', railCollapsed: true })
assert.deepEqual(parseDetailView('{"compareView":"wide","railCollapsed":"yes"}'), defaultDetailView, '未知取值回到默认展示')
assert.deepEqual(parseDetailView('{broken'), defaultDetailView, '损坏的本地偏好不能阻断页面')
assert.equal(initialDetailState('?kind=china&branch=OR&startDate=2026-09-01&endDate=2026-09-06').selection.branch, 'OR')
assert.equal(initialDetailState('?startDate=2026-02-30&endDate=2026-03-01').dates.quick, 'today')
assert.equal(initialDetailState('?kind=china&compare=0').dates.compare, false)
console.log('销售明细双向筛选、全量查询参数、本页合计、左栏宽度与展示偏好：通过')
