import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const page = readFileSync('src/pages/ExecutiveSalesIntelligence/SalesDetailAnalysisV2/index.tsx', 'utf8')
const hook = readFileSync('src/pages/ExecutiveSalesIntelligence/ReportWorkbench/useReportQuery.ts', 'utf8')
const css = readFileSync('src/pages/ExecutiveSalesIntelligence/SalesDetailAnalysisV2/styles.module.css', 'utf8')
const drawer = readFileSync('src/pages/ExecutiveSalesIntelligence/SalesDetailAnalysisV2/ProductBranchDrawer.tsx', 'utf8')
const logic = readFileSync('src/pages/ExecutiveSalesIntelligence/SalesDetailAnalysisV2/logic.ts', 'utf8')
const controls = readFileSync('src/pages/ExecutiveSalesIntelligence/ReportWorkbench/ReportControls.tsx', 'utf8')
assert.ok(controls.includes('compareMode: value.compareMode'), '快捷日期保留已选同比方式')
assert.ok(!controls.includes('maxDate='), '更换历史日期后不能把日历锁在旧区间')
assert.ok(page.indexOf('<Panel id="suppliers"') < page.indexOf('<Panel id="branches"'))
assert.ok(page.indexOf('<Panel id="branches"') < page.indexOf('<Panel id="products"'))
for (const marker of ['useKeepAliveContext', 'currentUser?.userGUID', 'aria-pressed', 'supplierCodes.includes(code)', 'selection.supplierCodes.length || selection.branch', 'onCompositionStart', 'onCompositionEnd', 'selectedProductCode']) assert.ok(page.includes(marker), marker)
assert.ok(page.includes('fetchSalesDetailReport(query, signal)'), '筛选和分页必须一次读取四栏完整 bundle')
assert.ok(page.includes('JSON.stringify([currentUser?.userGUID, branches, query])'), '整页查询键必须包含当前商品页')
assert.ok(!page.includes('productReport'), '不得把后续商品分页与先前供应商归属快照拼接')
assert.ok(page.includes("metricId: 'sales-detail-whole-page'"), '整页绘制耗时必须从 bundle 请求开始测量')
assert.ok(page.includes('MAX_SUPPLIER_SELECTIONS'), '分类选项请求必须遵守供应商数量上限')
assert.ok(page.includes('MAX_CATEGORY_SELECTIONS'), '分类多选必须遵守分类数量上限')
assert.ok(page.includes('分类选项共'), '分类选项超限必须明确提示，不能静默截断')
assert.ok(page.includes('appliedSearch.current === location.search'), 'KeepAlive 返回相同页面不能重置筛选')
assert.ok(page.includes("!active || !location.pathname.endsWith('/sales-detail-v2')"), '隐藏页面不消费其他页面 URL')
assert.ok(!page.includes('getBranchSalesAggregate'), '旧分店聚合口径不可继续使用')
assert.ok(!page.includes('storeCount'), '分店数不可冒充客单数')
assert.ok(page.includes("const sales: MetricKey[] = ['revenue', 'quantity', 'averageUnitPrice']"), '供应商、分店和商品统一展示营业额、商品数量与商品均价')
assert.ok(page.includes("return [...sales, ...shares, 'growth', ...profit]"), '份额和增长率必须排在毛利字段前，毛利额和毛利率固定在最后两列')
assert.ok(!page.includes('setMetricView'), '固定列顺序后不得保留会移动毛利列的视图切换')
assert.ok(page.includes("text('商品数量', 'Product quantity')"), '供应商和分店必须明确标注商品数量')
assert.ok(page.includes("text('商品均价', 'Average product price')"), '供应商和分店必须明确标注商品均价')
assert.ok(page.includes('right.quantity - left.quantity'), '商品当前页必须按本期数量降序防御性展示')
assert.ok(page.includes('setDrawerProduct(row)'), '商品行尾图标必须打开独立分店反查抽屉')
assert.ok(page.includes("onClick={() => pick('product', row)}"), '点击商品必须与供应商、分店一样联动另外两栏')
assert.ok(page.includes('data-view={compareView}'), '商品表必须支持上下 / 仅本期 / 左右三种同期展示')
assert.ok(page.includes("expanded === 'products' && !selection.product && total"), '选中商品时服务端汇总只含该商品，不能作为列表全部合计')
assert.ok(page.includes('<ProductBranchDrawer'), '销售明细必须挂载商品分店反查抽屉')
assert.ok(drawer.includes("fetchSalesDetailReport(drawerQuery, signal, ['branches'])"), '抽屉只能请求 branches 段')
assert.ok(drawer.includes('destroyOnHidden'), '抽屉关闭后应销毁可见内容')
for (const marker of ['selectedProductCode: productCode', 'selectedBranchCode: undefined', 'search: undefined']) assert.ok(logic.includes(marker), marker)
for (const marker of ['controller.abort()', 'state.key === key', 'disposed = true', '30000', 'performance.measure']) assert.ok(hook.includes(marker), marker)
assert.ok(css.includes('position:sticky'))
assert.ok(css.includes('height:calc(100dvh - var(--page-offset, 186px))'), '桌面端页面锁定在视口内，工作区吃满剩余高度')
assert.ok(page.includes("element.closest('.admin-content')"), '页面起点与底部留白按实际外壳测量，不写死顶栏与标签栏高度')
assert.ok(css.includes('.productTable tfoot td { position:sticky; bottom:0;'), '本页合计必须吸附在商品表底部并与列对齐')
assert.ok(css.includes('.drawerScroll'), '抽屉分店表必须支持横向滚动')
assert.ok(css.includes('prefers-reduced-motion'))
assert.ok(css.includes('@media(max-width:600px)'))
console.log('销售明细三栏、IME、取消、权限key与响应式契约：通过')
