import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const page = readFileSync('src/pages/ExecutiveSalesIntelligence/SalesDetailAnalysisV2/index.tsx', 'utf8')
const hook = readFileSync('src/pages/ExecutiveSalesIntelligence/ReportWorkbench/useReportQuery.ts', 'utf8')
const css = readFileSync('src/pages/ExecutiveSalesIntelligence/SalesDetailAnalysisV2/styles.module.css', 'utf8')
const controls = readFileSync('src/pages/ExecutiveSalesIntelligence/ReportWorkbench/ReportControls.tsx', 'utf8')
assert.ok(controls.includes('compareMode: value.compareMode'), '快捷日期保留已选同比方式')
assert.ok(!controls.includes('maxDate='), '更换历史日期后不能把日历锁在旧区间')
assert.ok(page.indexOf('<Panel id="suppliers"') < page.indexOf('<Panel id="branches"'))
assert.ok(page.indexOf('<Panel id="branches"') < page.indexOf('<Panel id="products"'))
for (const marker of ['useKeepAliveContext', 'currentUser?.userGUID', 'aria-pressed', 'onCompositionStart', 'onCompositionEnd', 'selectedProductCode', 'cacheVersion']) assert.ok(page.includes(marker), marker)
for (const section of ['suppliers', 'branches', 'products', 'summary']) assert.ok(page.includes(`retrySection('${section}')`), `${section} 独立重试`)
assert.ok(page.includes('appliedSearch.current === location.search'), 'KeepAlive 返回相同页面不能重置筛选')
assert.ok(page.includes("!active || !location.pathname.endsWith('/sales-detail-v2')"), '隐藏页面不消费其他页面 URL')
assert.ok(!page.includes('getBranchSalesAggregate'), '旧分店聚合口径不可继续使用')
assert.ok(!page.includes('storeCount'), '分店数不可冒充客单数')
for (const marker of ['controller.abort()', 'state.key === key', 'disposed = true', '30000', '12000', 'performance.measure']) assert.ok(hook.includes(marker), marker)
assert.ok(css.includes('position:sticky'))
assert.ok(css.includes('prefers-reduced-motion'))
assert.ok(css.includes('@media(max-width:600px)'))
console.log('销售明细三栏、IME、取消、权限key与响应式契约：通过')
