export const syncHistoryEnglishCopy = {
  "title": "Local sync history",
  "subtitle": "Review durable orders and request safe retransmission.",
  "pending.label": "Pending",
  "pending.count": "{{count}} orders",
  "action.back": "Back to sales",
  "action.refresh": "Refresh",
  "action.refreshing": "Refreshing…",
  "action.retransmitSelected": "Retransmit selected",
  "action.retransmitRange": "Retransmit date range",
  "action.loadMore": "Load more",
  "action.export": "Support export",
  "action.exporting": "Preparing…",
  "filters.title": "Filters",
  "filters.status": "Status",
  "filters.all": "All",
  "filters.dateFrom": "From date",
  "filters.dateTo": "To date",
  "filters.datePlaceholder": "YYYY-MM-DD",
  "filters.apply": "Apply filters",
  "selection.count": "{{count}} selected",
  "list.title": "Orders",
  "list.sequence": "Local #{{sequence}}",
  "list.order": "Order {{orderGuid}}",
  "list.amount": "Amount",
  "list.discount": "Discount",
  "list.tender": "Tender",
  "list.outbox": "Outbox",
  "list.attempts": "{{count}} attempts",
  "list.error": "Safe error: {{code}}",
  "list.nextAttempt": "Next attempt: {{time}}",
  "loading.title": "Loading local history…",
  "empty.title": "No local orders match these filters",
  "empty.hint": "Change the status or date range, then refresh.",
  "failed.title": "Local history could not be loaded",
  "failed.hint": "The encrypted ledger was not changed. Retry when ready.",
  "retransmit.requested": "{{count}} orders queued for retransmission.",
  "retransmit.none": "No selected orders are eligible for retransmission.",
  "retransmit.failed": "Retransmission was not requested.",
  "gate.reauthentication": "{{count}} orders require cashier re-authentication.",
  "gate.supervisor": "{{count}} rejected orders require supervisor review.",
  "gate.synced": "Already synced",
  "gate.syncing": "Sync in progress",
  "gate.reauthenticationRow": "Re-authenticate before retransmitting",
  "gate.supervisorRow": "Supervisor review required",
  "gate.noPending": "No pending outbox",
  "export.success": "A sanitized support export is ready.",
  "export.failed": "Support export failed. No diagnostic content was shown.",
  "status.CompletedLocal": "Completed locally",
  "status.PendingSync": "Pending sync",
  "status.Syncing": "Syncing",
  "status.Synced": "Synced",
  "status.Blocked403": "Re-authentication",
  "status.Rejected": "Supervisor review",
  "outbox.pending": "Queued",
  "outbox.leased": "Sending",
  "outbox.succeeded": "Delivered",
  "outbox.blocked403": "Blocked",
  "outbox.rejected": "Rejected",
} as const;

export type SyncHistoryCopyKey = keyof typeof syncHistoryEnglishCopy;

const syncHistoryChineseCopy = {
  "title": "本地同步历史",
  "subtitle": "查看耐久订单并安全发起补传。",
  "pending.label": "待同步",
  "pending.count": "{{count}} 笔",
  "action.back": "返回收银",
  "action.refresh": "刷新",
  "action.refreshing": "刷新中…",
  "action.retransmitSelected": "补传已选",
  "action.retransmitRange": "按日期范围补传",
  "action.loadMore": "加载更多",
  "action.export": "支持导出",
  "action.exporting": "正在准备…",
  "filters.title": "筛选",
  "filters.status": "状态",
  "filters.all": "全部",
  "filters.dateFrom": "开始日期",
  "filters.dateTo": "结束日期",
  "filters.datePlaceholder": "YYYY-MM-DD",
  "filters.apply": "应用筛选",
  "selection.count": "已选 {{count}} 笔",
  "list.title": "订单",
  "list.sequence": "本地序号 #{{sequence}}",
  "list.order": "订单 {{orderGuid}}",
  "list.amount": "实收",
  "list.discount": "折扣",
  "list.tender": "付款",
  "list.outbox": "补传队列",
  "list.attempts": "已尝试 {{count}} 次",
  "list.error": "安全错误码：{{code}}",
  "list.nextAttempt": "下次尝试：{{time}}",
  "loading.title": "正在读取本地历史…",
  "empty.title": "没有符合筛选条件的本地订单",
  "empty.hint": "调整状态或日期范围后刷新。",
  "failed.title": "无法读取本地历史",
  "failed.hint": "加密账本未被修改，可稍后重试。",
  "retransmit.requested": "已将 {{count}} 笔订单加入补传队列。",
  "retransmit.none": "已选订单均不符合补传条件。",
  "retransmit.failed": "未发起补传。",
  "gate.reauthentication": "{{count}} 笔订单需要收银员重新认证。",
  "gate.supervisor": "{{count}} 笔被拒订单需要主管处理。",
  "gate.synced": "已经同步",
  "gate.syncing": "正在同步",
  "gate.reauthenticationRow": "重新认证后方可补传",
  "gate.supervisorRow": "需要主管审核",
  "gate.noPending": "没有待处理补传任务",
  "export.success": "已生成脱敏的支持导出。",
  "export.failed": "支持导出失败，未显示任何诊断内容。",
  "status.CompletedLocal": "本地完成",
  "status.PendingSync": "待同步",
  "status.Syncing": "同步中",
  "status.Synced": "已同步",
  "status.Blocked403": "需要重新认证",
  "status.Rejected": "需要主管处理",
  "outbox.pending": "排队中",
  "outbox.leased": "发送中",
  "outbox.succeeded": "已送达",
  "outbox.blocked403": "已阻止",
  "outbox.rejected": "已拒绝",
} as const satisfies Record<SyncHistoryCopyKey, string>;

const syncHistoryCopy = {
  en: syncHistoryEnglishCopy,
  zh: syncHistoryChineseCopy,
} as const;

export type SyncHistoryLocale = keyof typeof syncHistoryCopy;

export function resolveSyncHistoryLocale(language?: string): SyncHistoryLocale {
  return language?.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function syncHistoryText(
  locale: SyncHistoryLocale,
  key: SyncHistoryCopyKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  const template = syncHistoryCopy[locale][key];
  if (!values) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name: string) => {
    const value = values[name];
    return value === undefined ? placeholder : String(value);
  });
}
