export const settingsEnglishCopy = {
  "header.eyebrow": "TERMINAL ADMIN",
  "header.title": "Settings",
  "header.subtitle":
    "Manage public runtime choices and local peripherals; protected credentials stay on the service.",
  "action.backToSales": "Back to sales",
  "navigation.title": "Sections",
  "navigation.general": "System & catalog",
  "navigation.payments": "Payment terminals",
  "navigation.peripherals": "Peripherals",
  "navigation.device": "Device registration",
  "navigation.hardware": "Hardware test",
  "device.currentTerminal": "Terminal",
  "device.unbound": "Unbound",
  "state.loading": "Loading terminal settings…",
  "state.failed": "Terminal settings unavailable",
  "state.unauthorized": "Settings permission required",
  "unavailable.eyebrow": "TERMINAL SETTINGS",
  "unavailable.title": "Settings unavailable",
  "unavailable.hint":
    "The settings adapter is not connected; no configuration or local data was changed.",
  "general.title": "System & catalog",
  "general.subtitle":
    "Endpoint changes require confirmation and a clear local queue.",
  "eyebrow.interaction": "INTERACTION",
  "general.soundFeedback": "Sound feedback",
  "general.buttonSound": "Button sounds",
  "general.buttonSoundHint":
    "Covers buttons, keys, page navigation and dangerous actions. Turn it on to hear a sample; turn it off to keep them silent.",
  "general.specialNodeSound": "Special event sounds",
  "general.specialNodeSoundHint":
    "Covers product lookup, cart add/increment, not-found and blocked results. Turn it on to hear a sample; turn it off to keep them silent.",
  "eyebrow.network": "NETWORK",
  "general.apiAddress": "API address",
  "general.useLocalApi": "Local backend",
  "general.useRemoteApi": "Remote backend",
  "general.testApiAddress": "Test connection",
  "general.reviewApiAddress": "Review change",
  "eyebrow.catalog": "CATALOG",
  "general.catalog": "Catalog",
  "metric.snapshot": "Snapshot",
  "metric.items": "Items",
  "metric.activated": "Activated",
  "value.none": "None",
  "general.downloadCatalog": "Download",
  "general.downloadingCatalog": "Refreshing…",
  "general.resetCatalog": "Review reset",
  "general.catalogSafety":
    "A failed download keeps the active catalog; reset never clears queued sales or returns.",
  "general.catalogBackground":
    "You can leave this page; the catalog continues refreshing inside the app, and the same progress is shown when you return.",
  "catalogRefresh.running": "Refreshing catalog",
  "catalogRefresh.success": "Catalog refreshed and activated",
  "catalogRefresh.warning": "Catalog activated with a safety warning",
  "catalogRefresh.failed":
    "Catalog refresh did not complete; the previous catalog remains available",
  "catalogRefresh.preparing": "Waiting for catalog preparation",
  "catalogRefresh.currentStep": "Current step: {{step}}",
  "catalogRefresh.step.prepare": "Prepare catalog",
  "catalogRefresh.step.products": "Download and verify items",
  "catalogRefresh.step.promotions": "Sync promotions",
  "catalogRefresh.step.activate": "Safe activation",
  "catalogRefresh.progress": "Overall progress: {{percent}}%",
  "catalogRefresh.elapsed": "Elapsed: {{elapsed}}",
  "catalogRefresh.items": "{{completed}} / {{total}} items",
  "catalogRefresh.pages": "{{completed}} / {{total}} pages",
  "catalogRefresh.safeCode": "Safe code: {{code}}",
  "eyebrow.updates": "UPDATES",
  "general.appUpdate": "App update",
  "metric.channel": "Channel",
  "metric.currentVersion": "Current",
  "metric.availableVersion": "Available",
  "value.current": "Current",
  "general.checkUpdate": "Check",
  "general.restart": "Review restart",
  "payments.title": "Payment terminals",
  "payments.subtitle":
    "Only public environment and terminal choices are stored here. Protected payment credentials are managed by the service.",
  "eyebrow.activeCardTerminal": "ACTIVE CARD TERMINAL",
  "payments.provider": "Card terminal provider",
  "payments.providerHint":
    "Select exactly one terminal provider; card payments remain disabled when no available provider is selected.",
  "payments.noneSelected": "Not selected: card payments disabled",
  "payments.squareSelected": "Square selected",
  "payments.linklySelected": "Linkly selected",
  "eyebrow.cardTerminal": "CARD TERMINAL",
  "field.locationId": "Location ID",
  "field.squareLocationId": "Square location ID",
  "field.deviceId": "Device ID",
  "field.squareDeviceId": "Square device ID",
  "square.serverToken": "Server Square access",
  "square.tokenReady": "Configured and enabled",
  "square.tokenDisabled": "Configured but disabled",
  "square.tokenMissing": "Not configured",
  "square.tokenIdle": "Server status not loaded",
  "square.tokenLoading": "Checking server status…",
  "square.tokenFailed": "Could not load server status",
  "square.setupUnavailable": "Square setup service unavailable",
  "square.currentBinding": "Current device binding",
  "square.location": "Location",
  "square.device": "Checkout device",
  "square.loadLocations": "Load locations",
  "square.loadDevices": "Load devices",
  "square.selectLocation": "Choose location",
  "square.selectDevice": "Choose device",
  "square.locationPickerTitle": "Choose a Square location",
  "square.devicePickerTitle": "Choose a Square checkout device",
  "square.locationPickerHint":
    "Select one server location. Its name is shown above the public ID and status.",
  "square.devicePickerHint":
    "Select one enabled checkout device for the chosen location.",
  "square.notSelected": "Not selected",
  "square.notLoaded": "Not loaded yet",
  "square.loadingLocations": "Loading Square locations…",
  "square.loadingDevices": "Loading Square devices…",
  "square.locationsEmpty": "No Square locations were returned.",
  "square.devicesEmpty": "No Square devices were returned for this location.",
  "square.loadFailed": "Could not load Square setup data. Try again.",
  "square.statusUnknown": "Status unavailable",
  "square.closePicker": "Close",
  "square.deviceCode": "Production Device Code",
  "square.deviceCodeName": "Device Code name",
  "square.deviceCodeNameHint":
    "Use a short name that identifies this checkout, then create one code only.",
  "square.loadDeviceCodes": "Load codes",
  "square.createDeviceCode": "Create code",
  "square.refreshDeviceCode": "Refresh current",
  "square.deviceCodesIdle": "Device Codes not loaded yet",
  "square.deviceCodesLoading": "Loading Device Codes…",
  "square.deviceCodesEmpty": "No Device Codes exist for this location.",
  "square.deviceCodePairing":
    "Enter the displayed code on the Square Terminal, complete pairing there, then refresh the current code to confirm its status.",
  "square.deviceCodeSandboxDisabled":
    "Sandbox uses official Square test devices; no Device Code needs to be created or paired.",
  "square.currentDeviceCode": "Current",
  "square.codePending": "Code pending",
  "action.test": "Test",
  "eyebrow.eftpos": "EFTPOS",
  "payments.linklyHint":
    "iPad uses the backend asynchronous Linkly channel; merchant authentication material is not stored here.",
  "payments.save": "Save payment choices",
  "peripherals.title": "Peripherals",
  "peripherals.subtitle":
    "Discover, connect and verify local printers, scanners and the external display.",
  "eyebrow.receipt": "RECEIPT",
  "peripherals.printer": "Printer",
  "peripherals.printing": "Printing",
  "peripherals.drawer": "Drawer",
  "printer.locale.en": "English",
  "printer.locale.zhCN": "Chinese",
  "printer.preferredN160": "Recommended target · printer001",
  "printer.deviceName": "Name",
  "printer.deviceAddress": "Device address (iOS UUID)",
  "field.peripheralId": "Peripheral ID",
  "field.printerPeripheralId": "Printer peripheral ID",
  "peripherals.scanPrinters": "Scan nearby",
  "action.save": "Save",
  "peripherals.testPrint": "Test",
  "peripherals.testDrawer": "Test drawer",
  "peripherals.clearSavedPrinter": "Clear saved printer",
  "action.connect": "Connect & Save",
  "printer.pickerTitle": "Choose a nearby Bluetooth device",
  "printer.pickerHint":
    "The scan shows every nearby Bluetooth Low Energy device. printer001 is the recommended target for the receipt printer.",
  "printer.scanning": "Scanning for nearby Bluetooth devices…",
  "printer.connecting": "Connecting and saving printer…",
  "printer.noneFound":
    "No nearby Bluetooth devices found. Make sure Bluetooth is on, then scan again.",
  "printer.bluetoothPermissionHint":
    "Allow HB POS to use Bluetooth in iPad Settings, then return to the app and scan again.",
  "action.openSystemSettings": "Open system settings",
  "eyebrow.scanner": "SCANNER",
  "peripherals.scanner": "Scanner",
  "label.status": "Status: {{status}}",
  "peripherals.captureOneScan": "Capture one scan",
  "eyebrow.customerDisplay": "CUSTOMER DISPLAY",
  "peripherals.externalDisplay": "External display",
  "action.enabled": "Enabled",
  "peripherals.testDisplay": "Test",
  "device.title": "Device registration",
  "device.subtitle":
    "Re-registration changes the trusted binding without deleting queued business records.",
  "eyebrow.currentBinding": "CURRENT BINDING",
  "device.currentBinding": "Current",
  "metric.store": "Store",
  "metric.storeName": "Store name",
  "metric.device": "Device",
  "eyebrow.reregister": "RE-REGISTER",
  "device.reregister": "Re-register",
  "field.targetStoreCode": "Target store code",
  "field.terminalName": "Terminal name",
  "device.reviewReregistration": "Review re-registration",
  "hardware.title": "Hardware test",
  "hardware.subtitle":
    "Verify each hardware path without creating a sale or payment.",
  "hardware.printTest": "Print test",
  "hardware.captureScan": "Capture scan",
  "hardware.showTest": "Show test",
  "hardware.display": "Display",
  "eyebrow.lastCapture": "LAST CAPTURE",
  "hardware.lastScan": "Last scan",
  "hardware.waitingForTest": "Waiting for test",
  "confirmation.body":
    "Local pending data is never cleared; any pending work blocks this action.",
  "action.cancel": "Cancel",
  "action.checking": "Checking…",
  "action.confirm": "Confirm",
  "environment.production": "Production",
  "environment.sandbox": "Sandbox",
  "availability.ready": "Runtime ready",
  "availability.unavailable": "Runtime unavailable{{blocker}}",
  "confirmation.changeApiAddress": "Change API address\n{{apiBaseUrl}}",
  "confirmation.changePaymentSettings": "Change payment terminal settings",
  "confirmation.resetCatalog": "Reset local catalog",
  "confirmation.reregisterDevice": "Re-register device to {{targetStoreCode}}",
  "confirmation.restartApp": "Restart app safely",
  "hardware.connected": "Connected",
  "hardware.ready": "Ready",
  "hardware.disconnected": "Disconnected",
  "hardware.unavailable": "Unavailable",
  "status.api-address-saved":
    "API address saved. The runtime must reconnect as directed by its adapter.",
  "status.api-health-check-failed":
    "Candidate API unavailable; previous address retained",
  "status.api-health-check-passed":
    "Candidate API is reachable; current address is unchanged",
  "status.app-restart-requested": "Safe restart requested",
  "status.app-update-check-failed": "Update check failed",
  "status.app-update-checked": "Update check complete",
  "status.cash-drawer-test-failed": "Cash drawer test failed",
  "status.cash-drawer-test-passed": "Cash drawer test sent",
  "status.cash-drawer-test-unknown":
    "Cash drawer command sent, but the printer did not confirm the result. Check the drawer manually; the app will not retry automatically.",
  "status.catalog-download-failed":
    "Download failed; current catalog remains active",
  "status.catalog-downloaded": "Catalog activated",
  "status.catalog-reset": "Local catalog reset",
  "status.catalog-reset-failed": "Catalog reset failed",
  "status.device-reregister-failed": "Re-registration did not start",
  "status.device-reregister-started": "Device re-registration started",
  "status.display-setting-failed": "Display setting failed",
  "status.display-setting-saved": "Display setting saved",
  "status.display-test-failed": "Display test failed",
  "status.display-test-passed": "Display test sent",
  "status.invalid-api-address": "Invalid API address",
  "status.invalid-device-registration": "Choose a different valid store",
  "status.load-failed": "Settings load failed",
  "status.payment-settings-invalid":
    "Public payment provider configuration is incomplete",
  "status.payment-settings-save-failed": "Payment settings save failed",
  "status.payment-settings-saved": "Payment settings saved",
  "status.payment-test-failed": "Payment test failed",
  "status.payment-test-passed": "Payment provider available",
  "status.pending-local-data": "Pending local work blocked the action",
  "status.permission-required": "Settings permission required",
  "status.printer-connect-failed":
    "Printer connection failed; settings were not saved",
  "status.printer-connected": "Printer connected and saved",
  "status.printer-connected-save-failed":
    "Printer connected, but settings could not be saved",
  "status.printer-clear-failed": "Saved printer could not be cleared",
  "status.printer-cleared": "Saved printer cleared",
  "status.printer-cleared-disconnect-failed":
    "Saved printer cleared, but the device may still be connected",
  "status.printer-bluetooth-authorization-pending":
    "Complete the iPad Bluetooth permission prompt, then scan again",
  "status.printer-bluetooth-permission-required":
    "Bluetooth permission is required to scan nearby devices",
  "status.printer-bluetooth-powered-off":
    "Bluetooth is off. Turn it on, then scan again",
  "status.printer-bluetooth-restricted":
    "Bluetooth access is restricted by iPad policy and cannot be changed here",
  "status.printer-scan-failed": "Printer scan failed",
  "status.printer-scan-finished": "Printer scan complete",
  "status.printer-settings-save-failed": "Printer settings save failed",
  "status.printer-settings-saved": "Printer settings saved",
  "status.printer-test-failed": "Test print failed",
  "status.printer-test-unknown":
    "Test command sent, but the printer did not confirm the result. Check the paper manually; the app will not retry automatically.",
  "status.printer-test-passed": "Test receipt sent",
  "status.restart-failed": "Restart or endpoint change failed",
  "status.safety-check-failed": "Safety state unavailable; action blocked",
  "status.scanner-test-failed": "Scanner test failed",
  "status.scanner-test-passed": "Scan received",
} as const;

export type SettingsCopyKey = keyof typeof settingsEnglishCopy;

export const settingsChineseCopy = {
  "header.eyebrow": "终端管理",
  "header.title": "设置",
  "header.subtitle":
    "管理公开运行参数与本机外设；支付凭据和设备密钥始终留在受保护服务中。",
  "action.backToSales": "返回销售页",
  "navigation.title": "设置分区",
  "navigation.general": "系统与目录",
  "navigation.payments": "支付终端",
  "navigation.peripherals": "外设",
  "navigation.device": "设备注册",
  "navigation.hardware": "硬件测试",
  "device.currentTerminal": "当前终端",
  "device.unbound": "未绑定",
  "state.loading": "正在读取本机设置…",
  "state.failed": "本机设置暂不可读",
  "state.unauthorized": "没有查看设置权限",
  "unavailable.eyebrow": "终端设置",
  "unavailable.title": "设置服务暂不可用",
  "unavailable.hint":
    "本机运行时尚未接入设置适配器，未执行任何配置或数据变更。",
  "general.title": "系统与商品目录",
  "general.subtitle":
    "切换服务地址会改变数据分区，必须确认且本机无待处理交易。",
  "eyebrow.interaction": "交互反馈",
  "general.soundFeedback": "音效反馈",
  "general.buttonSound": "普通按钮音效",
  "general.buttonSoundHint":
    "覆盖按钮、按键、页面导航和危险操作；开启时播放一次示例，关闭后保持静音。",
  "general.specialNodeSound": "特殊节点音效",
  "general.specialNodeSoundHint":
    "覆盖商品查询、加购/累加、未找到和受阻结果；开启时播放一次示例，关闭后保持静音。",
  "eyebrow.network": "网络",
  "general.apiAddress": "API 地址",
  "general.useLocalApi": "本地后端",
  "general.useRemoteApi": "远程后端",
  "general.testApiAddress": "测试连接",
  "general.reviewApiAddress": "检查并申请切换",
  "eyebrow.catalog": "目录",
  "general.catalog": "商品目录",
  "metric.snapshot": "快照",
  "metric.items": "商品数",
  "metric.activated": "启用时间",
  "value.none": "无",
  "general.downloadCatalog": "下载并安全启用",
  "general.downloadingCatalog": "正在刷新…",
  "general.resetCatalog": "申请重置",
  "general.catalogSafety":
    "下载失败时保留当前已验证目录；重置前不会清除待同步销售或退款。",
  "general.catalogBackground":
    "可离开本页，目录会在应用内继续刷新；返回后仍显示相同进度。",
  "catalogRefresh.running": "正在刷新目录",
  "catalogRefresh.success": "目录已在后台完成并启用",
  "catalogRefresh.warning": "目录已启用，但有安全警告",
  "catalogRefresh.failed": "目录刷新未完成，旧目录仍可用",
  "catalogRefresh.preparing": "正在等待目录准备",
  "catalogRefresh.currentStep": "当前步骤：{{step}}",
  "catalogRefresh.step.prepare": "准备目录",
  "catalogRefresh.step.products": "下载并校验商品",
  "catalogRefresh.step.promotions": "同步促销",
  "catalogRefresh.step.activate": "安全激活",
  "catalogRefresh.progress": "总进度：{{percent}}%",
  "catalogRefresh.elapsed": "已用时：{{elapsed}}",
  "catalogRefresh.items": "{{completed}} / {{total}} 件商品",
  "catalogRefresh.pages": "{{completed}} / {{total}} 页",
  "catalogRefresh.safeCode": "安全码：{{code}}",
  "eyebrow.updates": "更新",
  "general.appUpdate": "应用更新",
  "metric.channel": "渠道",
  "metric.currentVersion": "当前版本",
  "metric.availableVersion": "可用版本",
  "value.current": "已是最新",
  "general.checkUpdate": "检查更新",
  "general.restart": "申请安全重启",
  "payments.title": "支付终端",
  "payments.subtitle":
    "这里只保存公开的环境、门店和终端选择；受保护支付凭据由服务端管理。",
  "eyebrow.activeCardTerminal": "当前刷卡终端",
  "payments.provider": "刷卡终端提供方",
  "payments.providerHint":
    "必须明确选择一个终端提供方；未选择或所选终端不可用时，银行卡支付保持关闭。",
  "payments.noneSelected": "未选择：银行卡支付已关闭",
  "payments.squareSelected": "已选择 Square",
  "payments.linklySelected": "已选择 Linkly",
  "eyebrow.cardTerminal": "刷卡终端",
  "field.locationId": "门店位置 ID",
  "field.squareLocationId": "Square 门店位置 ID",
  "field.deviceId": "终端设备 ID",
  "field.squareDeviceId": "Square 终端设备 ID",
  "square.serverToken": "服务端 Square 授权",
  "square.tokenReady": "已配置且已启用",
  "square.tokenDisabled": "已配置但已停用",
  "square.tokenMissing": "尚未配置",
  "square.tokenIdle": "尚未加载服务端状态",
  "square.tokenLoading": "正在检查服务端状态…",
  "square.tokenFailed": "无法加载服务端状态",
  "square.setupUnavailable": "Square 设置服务不可用",
  "square.currentBinding": "本机当前绑定",
  "square.location": "门店位置",
  "square.device": "收银终端",
  "square.loadLocations": "加载位置",
  "square.loadDevices": "加载终端",
  "square.selectLocation": "选择位置",
  "square.selectDevice": "选择终端",
  "square.locationPickerTitle": "选择 Square 门店位置",
  "square.devicePickerTitle": "选择 Square 收银终端",
  "square.locationPickerHint": "从服务端位置中选择一项；主行显示名称，次行显示公开 ID 与状态。",
  "square.devicePickerHint": "为当前门店位置选择一台已启用的收银终端。",
  "square.notSelected": "尚未选择",
  "square.notLoaded": "尚未加载",
  "square.loadingLocations": "正在加载 Square 门店位置…",
  "square.loadingDevices": "正在加载 Square 终端…",
  "square.locationsEmpty": "服务端未返回 Square 门店位置。",
  "square.devicesEmpty": "当前门店位置没有可用的 Square 终端。",
  "square.loadFailed": "无法加载 Square 设置，请重试。",
  "square.statusUnknown": "状态未知",
  "square.closePicker": "关闭",
  "square.deviceCode": "Production Device Code",
  "square.deviceCodeName": "配对码名称",
  "square.deviceCodeNameHint": "使用可识别当前收银台的简短名称；每次只创建一个配对码。",
  "square.loadDeviceCodes": "加载配对码",
  "square.createDeviceCode": "创建配对码",
  "square.refreshDeviceCode": "刷新当前状态",
  "square.deviceCodesIdle": "尚未加载配对码",
  "square.deviceCodesLoading": "正在加载 Device Code…",
  "square.deviceCodesEmpty": "当前门店位置尚无 Device Code。",
  "square.deviceCodePairing":
    "在 Square Terminal 上输入显示的配对码并完成配对，然后手动刷新当前状态确认结果。",
  "square.deviceCodeSandboxDisabled":
    "Sandbox 使用 Square 官方测试终端，无需创建或配对 Device Code。",
  "square.currentDeviceCode": "当前",
  "square.codePending": "等待生成配对码",
  "action.test": "测试可用性",
  "eyebrow.eftpos": "刷卡终端",
  "payments.linklyHint":
    "iPad 使用后端异步 Linkly 通道。商户与 POS 认证材料不会进入本机普通设置。",
  "payments.save": "保存支付终端选择",
  "peripherals.title": "外设",
  "peripherals.subtitle": "发现、连接并验证本机打印机、扫描器与独立客显。",
  "eyebrow.receipt": "小票",
  "peripherals.printer": "小票打印机",
  "peripherals.printing": "打印",
  "peripherals.drawer": "钱箱",
  "printer.locale.en": "英文",
  "printer.locale.zhCN": "中文",
  "printer.preferredN160": "推荐目标",
  "printer.deviceName": "名称",
  "printer.deviceAddress": "设备地址（iOS UUID）",
  "field.peripheralId": "设备 ID",
  "field.printerPeripheralId": "打印机设备 ID",
  "peripherals.scanPrinters": "扫描附近设备",
  "action.save": "保存",
  "peripherals.testPrint": "测试打印",
  "peripherals.testDrawer": "测试钱箱",
  "peripherals.clearSavedPrinter": "清除已保存打印机",
  "action.connect": "连接并保存",
  "printer.pickerTitle": "选择附近的蓝牙设备",
  "printer.pickerHint":
    "扫描结果会显示附近所有低功耗蓝牙设备；printer001 是推荐目标。",
  "printer.scanning": "正在扫描附近的蓝牙设备…",
  "printer.connecting": "正在连接并保存打印机…",
  "printer.noneFound":
    "未发现附近的蓝牙设备。请确认蓝牙已开启，然后重新扫描。",
  "printer.bluetoothPermissionHint":
    "请在 iPad 系统设置中允许 HB POS 使用蓝牙，然后返回应用重新扫描。",
  "action.openSystemSettings": "前往系统设置",
  "eyebrow.scanner": "扫描器",
  "peripherals.scanner": "扫描器",
  "label.status": "状态：{{status}}",
  "peripherals.captureOneScan": "等待一次扫码",
  "eyebrow.customerDisplay": "客显",
  "peripherals.externalDisplay": "独立客显",
  "action.enabled": "启用",
  "peripherals.testDisplay": "测试画面",
  "device.title": "设备注册",
  "device.subtitle": "重新注册只改变可信设备绑定，不会删除本地待同步业务记录。",
  "eyebrow.currentBinding": "当前绑定",
  "device.currentBinding": "当前绑定",
  "metric.store": "门店",
  "metric.storeName": "门店名称",
  "metric.device": "设备",
  "eyebrow.reregister": "重新注册",
  "device.reregister": "重新注册",
  "field.targetStoreCode": "目标门店代码",
  "field.terminalName": "终端名称",
  "device.reviewReregistration": "检查并申请重新注册",
  "hardware.title": "硬件测试",
  "hardware.subtitle": "逐项验证硬件链路；测试不会创建销售或支付。",
  "hardware.printTest": "打印测试小票",
  "hardware.captureScan": "等待一次扫码",
  "hardware.showTest": "显示测试画面",
  "hardware.display": "独立客显",
  "eyebrow.lastCapture": "最近扫码",
  "hardware.lastScan": "最近扫码",
  "hardware.waitingForTest": "等待测试",
  "confirmation.body":
    "确认前会再次检查活动购物车、待同步销售或退款、未决支付与耐久写入。待同步数据不会被清除；存在任何项目时操作会被阻断。",
  "action.cancel": "取消",
  "action.checking": "检查中…",
  "action.confirm": "确认执行",
  "environment.production": "生产",
  "environment.sandbox": "沙盒",
  "availability.ready": "运行时可用",
  "availability.unavailable": "运行时未配置{{blocker}}",
  "confirmation.changeApiAddress": "切换 API 地址\n{{apiBaseUrl}}",
  "confirmation.changePaymentSettings": "切换支付终端配置",
  "confirmation.resetCatalog": "重置本地商品目录",
  "confirmation.reregisterDevice": "重新注册到 {{targetStoreCode}}",
  "confirmation.restartApp": "安全重启应用",
  "hardware.connected": "已连接",
  "hardware.ready": "就绪",
  "hardware.disconnected": "未连接",
  "hardware.unavailable": "不可用",
  "status.api-address-saved":
    "API 地址已保存；运行时必须按适配器指引重新建立。",
  "status.api-health-check-failed": "候选 API 健康检查失败，旧地址保持不变",
  "status.api-health-check-passed": "候选 API 连接成功，当前地址尚未切换",
  "status.app-restart-requested": "已请求安全重启",
  "status.app-update-check-failed": "更新检查失败",
  "status.app-update-checked": "更新检查完成",
  "status.cash-drawer-test-failed": "钱箱测试失败",
  "status.cash-drawer-test-passed": "钱箱测试指令已发送",
  "status.cash-drawer-test-unknown":
    "钱箱指令已发送，但打印机未确认结果；请人工检查钱箱，应用不会自动重试。",
  "status.catalog-download-failed": "目录下载失败，当前目录仍可用",
  "status.catalog-downloaded": "目录已下载并启用",
  "status.catalog-reset": "本地目录已重置",
  "status.catalog-reset-failed": "目录重置失败",
  "status.device-reregister-failed": "重新注册未开始",
  "status.device-reregister-started": "设备重新注册已开始",
  "status.display-setting-failed": "客显设置失败",
  "status.display-setting-saved": "客显设置已保存",
  "status.display-test-failed": "客显测试失败",
  "status.display-test-passed": "客显测试已发送",
  "status.invalid-api-address": "API 地址格式不安全",
  "status.invalid-device-registration": "请选择不同的有效门店",
  "status.load-failed": "读取设置失败",
  "status.payment-settings-invalid": "可用支付通道的公开配置不完整",
  "status.payment-settings-save-failed": "支付终端设置保存失败",
  "status.payment-settings-saved": "支付终端设置已保存",
  "status.payment-test-failed": "支付通道测试失败",
  "status.payment-test-passed": "支付通道可用",
  "status.pending-local-data": "存在本地待处理业务，操作已阻断且数据保持不变",
  "status.permission-required": "需要相应设置权限",
  "status.printer-connect-failed": "打印机连接失败，设置未保存",
  "status.printer-connected": "打印机已连接并保存",
  "status.printer-connected-save-failed": "打印机已连接，但设置保存失败",
  "status.printer-clear-failed": "未能清除已保存的打印机",
  "status.printer-cleared": "已清除保存的打印机",
  "status.printer-cleared-disconnect-failed":
    "已清除保存的打印机，但设备可能仍保持连接",
  "status.printer-bluetooth-authorization-pending":
    "请先完成 iPad 蓝牙授权弹窗，然后重新扫描",
  "status.printer-bluetooth-permission-required":
    "扫描附近设备需要蓝牙权限",
  "status.printer-bluetooth-powered-off": "蓝牙已关闭，请开启后重新扫描",
  "status.printer-bluetooth-restricted":
    "蓝牙访问受到 iPad 系统策略限制，无法在此解除",
  "status.printer-scan-failed": "打印机扫描失败",
  "status.printer-scan-finished": "打印机扫描完成",
  "status.printer-settings-save-failed": "打印机设置保存失败",
  "status.printer-settings-saved": "打印机设置已保存",
  "status.printer-test-failed": "测试打印失败",
  "status.printer-test-unknown":
    "测试命令已发送，但打印机未确认结果；请人工检查是否出纸，应用不会自动重试。",
  "status.printer-test-passed": "测试小票已发送",
  "status.restart-failed": "重启或地址切换失败",
  "status.safety-check-failed": "无法确认本地安全状态，操作已阻断",
  "status.scanner-test-failed": "扫码测试失败",
  "status.scanner-test-passed": "已收到扫码",
} as const satisfies Record<SettingsCopyKey, string>;

const settingsCopy = {
  en: settingsEnglishCopy,
  zh: settingsChineseCopy,
} as const;

export type SettingsLocale = keyof typeof settingsCopy;

export function resolveSettingsLocale(language?: string): SettingsLocale {
  return language?.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function settingsText(
  locale: SettingsLocale,
  key: SettingsCopyKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  const template = settingsCopy[locale][key];
  if (!values) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name: string) => {
    const value = values[name];
    return value === undefined ? placeholder : String(value);
  });
}
