/* HOT_POS_CLOUD v1 -> v2：仅原位重建已部署的明细索引，使其覆盖 B商品名。仅供人工运维执行，禁止接入应用启动或迁移。 */
USE [HOT_POS_CLOUD];
GO
SET NOCOUNT ON; SET XACT_ABORT ON; SET DEADLOCK_PRIORITY LOW;
DECLARE @oid int=OBJECT_ID(N'dbo.B销售清单详情表副本'),@idx sysname=N'IX_B销售清单详情表副本_折扣日日期单号',@v1 nvarchar(256)=N'hb-discount-source-index-repair-20260915:v1',@v2 nvarchar(256)=N'hb-discount-source-index-repair-20260915:v2-productname';
DECLARE @old nvarchar(max)=N'K:B结账日期 ASC;K:B销售单号 ASC;I:B分店代码;I:B产品编号;I:B货号;I:B供应商ID;I:B条形码;I:B单价;I:B折扣率;I:B数量;I:B原价合计金额;I:B合计金额;I:B单位;I:B退货码;I:FGC_CreateDate;I:FGC_LastModifyDate';
DECLARE @new nvarchar(max)=N'K:B结账日期 ASC;K:B销售单号 ASC;I:B分店代码;I:B产品编号;I:B货号;I:B供应商ID;I:B商品名;I:B条形码;I:B单价;I:B折扣率;I:B数量;I:B原价合计金额;I:B合计金额;I:B单位;I:B退货码;I:FGC_CreateDate;I:FGC_LastModifyDate';
IF DB_NAME()<>N'HOT_POS_CLOUD' OR @@SERVERNAME<>N'10_3_8_3' THROW 51600,N'拒绝：实例或数据库不匹配。',1;
IF NOT EXISTS(SELECT 1 FROM sys.database_recovery_status WHERE database_id=DB_ID() AND database_guid='0C518478-C3A0-4B2B-BCA2-164427670C88') THROW 51601,N'拒绝：database_guid 不匹配。',1;
IF TRY_CONVERT(int,SERVERPROPERTY('ProductMajorVersion'))<>16 OR CONVERT(nvarchar(256),SERVERPROPERTY('Edition')) NOT LIKE N'Developer Edition%' THROW 51602,N'拒绝：SQL Edition/版本不匹配。',1;
IF @oid IS NULL OR NOT EXISTS(SELECT 1 FROM sys.columns WHERE object_id=@oid AND name=N'B结账日期' AND system_type_id=40) OR NOT EXISTS(SELECT 1 FROM sys.columns WHERE object_id=@oid AND name=N'B销售单号' AND system_type_id=231 AND max_length=100) OR NOT EXISTS(SELECT 1 FROM sys.columns WHERE object_id=@oid AND name=N'B商品名' AND system_type_id=231 AND max_length=1000) THROW 51603,N'拒绝：目标关键列类型/长度不匹配。',1;
/* 前态必须精确匹配：归属标记、升序键顺序、索引物理选项及压缩状态均受保护。 */
IF NOT EXISTS(SELECT 1 FROM sys.indexes i JOIN sys.stats st ON st.object_id=i.object_id AND st.stats_id=i.index_id JOIN sys.extended_properties ep ON ep.class=7 AND ep.major_id=i.object_id AND ep.minor_id=i.index_id AND ep.name=N'HB_DiscountSourceIndex_20260915_Owner' AND CONVERT(nvarchar(256),ep.value)=@v1
 WHERE i.object_id=@oid AND i.name=@idx AND i.type=2 AND i.is_unique=0 AND i.is_primary_key=0 AND i.is_unique_constraint=0 AND i.is_disabled=0 AND i.is_hypothetical=0 AND i.has_filter=0 AND i.fill_factor=0 AND i.is_padded=0 AND i.ignore_dup_key=0 AND i.suppress_dup_key_messages=0 AND i.auto_created=0 AND i.optimize_for_sequential_key=0 AND i.allow_row_locks=1 AND i.allow_page_locks=1 AND i.data_space_id=1 AND st.no_recompute=0 AND st.is_incremental=0 AND st.has_persisted_sample=0
 AND NOT EXISTS(SELECT 1 FROM sys.partitions p WHERE p.object_id=i.object_id AND p.index_id=i.index_id AND (p.data_compression<>0 OR p.xml_compression<>0))
 AND (SELECT STRING_AGG(CONCAT(CASE WHEN ic.is_included_column=1 THEN N'I:' ELSE N'K:' END,c.name,CASE WHEN ic.key_ordinal>0 AND ic.is_descending_key=1 THEN N' DESC' WHEN ic.key_ordinal>0 THEN N' ASC' ELSE N'' END),N';') WITHIN GROUP(ORDER BY CASE WHEN ic.is_included_column=0 THEN 0 ELSE 1 END,ic.key_ordinal,ic.index_column_id) FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE ic.object_id=i.object_id AND ic.index_id=i.index_id)=@old) THROW 51604,N'拒绝：v1索引物理定义或归属不匹配。',1;
DECLARE @rows bigint=(SELECT SUM(row_count) FROM sys.dm_db_partition_stats WHERE object_id=@oid AND index_id IN(0,1));
DECLARE @oldMB decimal(19,1)=(SELECT SUM(reserved_page_count)*8.0/1024 FROM sys.dm_db_partition_stats WHERE object_id=@oid AND index_id=(SELECT index_id FROM sys.indexes WHERE object_id=@oid AND name=@idx));
/* 按 nvarchar(500) 最大 1000 字节、每行额外 16 字节和 1.25 系数保守估算；重建期间新旧索引会并存。 */
DECLARE @buildMB decimal(19,1)=CEILING((@oldMB+@rows*CAST(1016 AS decimal(28,4))/1048576.0)*1.25),@rowsFreeMB decimal(19,1),@logFreeMB decimal(19,1),@volumeFreeMB decimal(19,1),@rowsGrowMB decimal(19,1),@logGrowMB decimal(19,1),@rowsCapacityMB decimal(19,1),@logCapacityMB decimal(19,1),@oneVolume bit,@recovery nvarchar(60),@reuse nvarchar(60),@logNeedMB decimal(19,1),@rowsGrowthNeededMB decimal(19,1),@logGrowthNeededMB decimal(19,1);
SELECT @rowsFreeMB=SUM((size-FILEPROPERTY(name,'SpaceUsed'))*8.0/1024),@rowsGrowMB=SUM(CASE WHEN max_size=-1 THEN 0 ELSE (max_size-size)*8.0/1024 END) FROM sys.database_files WHERE type_desc=N'ROWS';
SELECT @logFreeMB=(total_log_size_in_bytes-used_log_space_in_bytes)/1048576.0 FROM sys.dm_db_log_space_usage; SELECT @recovery=recovery_model_desc,@reuse=log_reuse_wait_desc FROM sys.databases WHERE database_id=DB_ID();
SELECT @logGrowMB=SUM(CASE WHEN max_size=-1 THEN 0 ELSE (max_size-size)*8.0/1024 END) FROM sys.database_files WHERE type_desc=N'LOG';
SELECT @volumeFreeMB=MIN(vs.available_bytes/1048576.0),@oneVolume=CASE WHEN COUNT(DISTINCT CONVERT(nvarchar(4000),vs.volume_mount_point))=1 THEN 1 ELSE 0 END FROM sys.database_files f CROSS APPLY sys.dm_os_volume_stats(DB_ID(),f.file_id) vs;
SET @rowsCapacityMB=@rowsFreeMB+CASE WHEN EXISTS(SELECT 1 FROM sys.database_files WHERE type_desc=N'ROWS' AND max_size=-1) THEN @volumeFreeMB ELSE @rowsGrowMB END;
SET @logNeedMB=@buildMB*2; SET @logCapacityMB=@logFreeMB+CASE WHEN EXISTS(SELECT 1 FROM sys.database_files WHERE type_desc=N'LOG' AND max_size=-1) THEN @volumeFreeMB ELSE @logGrowMB END;
SET @rowsGrowthNeededMB=CASE WHEN @buildMB>@rowsFreeMB THEN @buildMB-@rowsFreeMB ELSE 0 END;
SET @logGrowthNeededMB=CASE WHEN @logNeedMB>@logFreeMB THEN @logNeedMB-@logFreeMB ELSE 0 END;
SELECT N'COVER_PRODUCTNAME_GUARD' Guard,@rows Rows,@oldMB OldIndexReservedMB,@buildMB ConservativeNewBuildMB,@rowsFreeMB RowsInternalFreeMB,@logFreeMB LogInternalFreeMB,@logNeedMB ConservativeLogNeedMB,@recovery RecoveryModel,@reuse LogReuseWait,@rowsCapacityMB RowsLogicalCapacityMB,@logCapacityMB LogLogicalCapacityMB,@volumeFreeMB SharedVolumeFreeMB,@oneVolume RowsAndLogShareOneVolume,@rowsGrowthNeededMB RowsGrowthNeededMB,@logGrowthNeededMB LogGrowthNeededMB;
IF @rows IS NULL OR @oldMB IS NULL OR @buildMB IS NULL OR @rowsFreeMB IS NULL OR @logFreeMB IS NULL OR @volumeFreeMB IS NULL OR @rowsCapacityMB IS NULL OR @logCapacityMB IS NULL OR @oneVolume IS NULL OR @recovery IS NULL OR @reuse IS NULL OR @oneVolume<>1 OR @recovery<>N'FULL' OR @reuse NOT IN(N'NOTHING',N'LOG_BACKUP') OR @rowsCapacityMB<@buildMB OR @logCapacityMB<@logNeedMB OR @volumeFreeMB < @rowsGrowthNeededMB+@logGrowthNeededMB+8192 OR EXISTS(SELECT 1 FROM sys.database_files WHERE type_desc=N'ROWS' AND NOT(max_size=-1 AND growth=8192 AND is_percent_growth=0)) OR EXISTS(SELECT 1 FROM sys.database_files WHERE type_desc=N'LOG' AND NOT(max_size=268435456 AND growth=8192 AND is_percent_growth=0)) THROW 51605,N'拒绝：build/data/log/共享卷运营余量、文件增长/max_size 或恢复模型不满足。',1;
SET LOCK_TIMEOUT -1;
BEGIN TRY BEGIN TRANSACTION;
 CREATE NONCLUSTERED INDEX [IX_B销售清单详情表副本_折扣日日期单号] ON dbo.[B销售清单详情表副本]([B结账日期] ASC,[B销售单号] ASC) INCLUDE([B分店代码],[B产品编号],[B货号],[B供应商ID],[B商品名],[B条形码],[B单价],[B折扣率],[B数量],[B原价合计金额],[B合计金额],[B单位],[B退货码],[FGC_CreateDate],[FGC_LastModifyDate]) WITH(DROP_EXISTING=ON,ONLINE=ON (WAIT_AT_LOW_PRIORITY(MAX_DURATION=5 MINUTES,ABORT_AFTER_WAIT=SELF)),MAXDOP=1,SORT_IN_TEMPDB=OFF);
 IF EXISTS(SELECT 1 FROM sys.extended_properties ep JOIN sys.indexes i ON i.object_id=ep.major_id AND i.index_id=ep.minor_id WHERE ep.class=7 AND i.object_id=@oid AND i.name=@idx AND ep.name=N'HB_DiscountSourceIndex_20260915_Owner') EXEC sys.sp_updateextendedproperty @name=N'HB_DiscountSourceIndex_20260915_Owner',@value=@v2,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'B销售清单详情表副本',@level2type=N'INDEX',@level2name=@idx; ELSE EXEC sys.sp_addextendedproperty @name=N'HB_DiscountSourceIndex_20260915_Owner',@value=@v2,@level0type=N'SCHEMA',@level0name=N'dbo',@level1type=N'TABLE',@level1name=N'B销售清单详情表副本',@level2type=N'INDEX',@level2name=@idx;
 IF NOT EXISTS(SELECT 1 FROM sys.indexes i JOIN sys.stats st ON st.object_id=i.object_id AND st.stats_id=i.index_id JOIN sys.extended_properties ep ON ep.class=7 AND ep.major_id=i.object_id AND ep.minor_id=i.index_id AND ep.name=N'HB_DiscountSourceIndex_20260915_Owner' AND CONVERT(nvarchar(256),ep.value)=@v2 WHERE i.object_id=@oid AND i.name=@idx AND i.type=2 AND i.is_unique=0 AND i.is_primary_key=0 AND i.is_unique_constraint=0 AND i.is_disabled=0 AND i.is_hypothetical=0 AND i.has_filter=0 AND i.fill_factor=0 AND i.is_padded=0 AND i.ignore_dup_key=0 AND i.suppress_dup_key_messages=0 AND i.auto_created=0 AND i.optimize_for_sequential_key=0 AND i.allow_row_locks=1 AND i.allow_page_locks=1 AND i.data_space_id=1 AND st.no_recompute=0 AND st.is_incremental=0 AND st.has_persisted_sample=0 AND NOT EXISTS(SELECT 1 FROM sys.partitions p WHERE p.object_id=i.object_id AND p.index_id=i.index_id AND (p.data_compression<>0 OR p.xml_compression<>0)) AND (SELECT STRING_AGG(CONCAT(CASE WHEN ic.is_included_column=1 THEN N'I:' ELSE N'K:' END,c.name,CASE WHEN ic.key_ordinal>0 AND ic.is_descending_key=1 THEN N' DESC' WHEN ic.key_ordinal>0 THEN N' ASC' ELSE N'' END),N';') WITHIN GROUP(ORDER BY CASE WHEN ic.is_included_column=0 THEN 0 ELSE 1 END,ic.key_ordinal,ic.index_column_id) FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE ic.object_id=i.object_id AND ic.index_id=i.index_id)=@new) THROW 51606,N'拒绝：重建后定义/owner不匹配。',1;
 COMMIT TRANSACTION; END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK TRANSACTION; THROW; END CATCH;
GO
