export const settingsEnglishCopy = {
  "header.eyebrow": "TERMINAL ADMIN",
  "header.title": "Settings",
  "header.subtitle":
    "Manage public runtime choices and local peripherals; protected credentials stay on the service.",
  "action.backToSales": "Back to sales",
  "navigation.title": "Sections",
  "navigation.general": "System & catalog",
  "navigation.payments": "Payment terminals",
  "navigation.peripherals": "Peripherals",
  "navigation.device": "Device registration",
  "navigation.hardware": "Hardware test",
  "device.currentTerminal": "Terminal",
  "device.unbound": "Unbound",
  "state.loading": "Loading terminal settings…",
  "state.failed": "Terminal settings unavailable",
  "state.unauthorized": "Settings permission required",
  "unavailable.eyebrow": "TERMINAL SETTINGS",
  "unavailable.title": "Settings unavailable",
  "unavailable.hint":
    "The settings adapter is not connected; no configuration or local data was changed.",
  "general.title": "System & catalog",
  "general.subtitle":
    "Endpoint changes require confirmation and a clear local queue.",
  "general.terminalPreferences": "Transaction, language & security",
  "general.language": "Language",
  "general.switchLanguage": "中文",
  "general.singleScreen":
    "Single-screen handheld terminal; secondary-screen controls are not available.",
  "general.securityHint":
    "Transaction access remains cashier-scoped and protected by the automatic lock policy.",
  "eyebrow.interaction": "INTERACTION",
  "general.soundFeedback": "Sound feedback",
  "general.buttonSound": "Button sounds",
  "general.buttonSoundHint":
    "Covers buttons, keys, page navigation and dangerous actions. Turn it on to hear a sample; turn it off to keep them silent.",
  "general.specialNodeSound": "Special event sounds",
  "general.specialNodeSoundHint":
    "Covers product lookup, cart add/increment, not-found and blocked results. Turn it on to hear a sample; turn it off to keep them silent.",
  "eyebrow.network": "NETWORK",
  "general.apiAddress": "API address",
  "general.useLocalApi": "Local backend",
  "general.useRemoteApi": "Remote backend",
  "general.testApiAddress": "Test connection",
  "general.reviewApiAddress": "Review change",
  "eyebrow.catalog": "CATALOG",
  "general.catalog": "Catalog",
  "metric.snapshot": "Snapshot",
  "metric.items": "Items",
  "metric.activated": "Activated",
  "value.none": "None",
  "general.downloadCatalog": "Download",
  "general.downloadingCatalog": "Refreshing…",
  "general.resetCatalog": "Review reset",
  "general.catalogSafety":
    "A failed download keeps the active catalog; reset never clears queued sales or returns.",
  "general.catalogBackground":
    "You can leave this page; the catalog continues refreshing inside the app, and the same progress is shown when you return.",
  "catalogRefresh.running": "Refreshing catalog",
  "catalogRefresh.success": "Catalog refreshed and activated",
  "catalogRefresh.warning": "Catalog activated with a safety warning",
  "catalogRefresh.failed":
    "Catalog refresh did not complete; the previous catalog remains available",
  "catalogRefresh.preparing": "Waiting for catalog preparation",
  "catalogRefresh.currentStep": "Current step: {{step}}",
  "catalogRefresh.step.prepare": "Prepare catalog",
  "catalogRefresh.step.products": "Download and verify items",
  "catalogRefresh.step.promotions": "Sync promotions",
  "catalogRefresh.step.activate": "Safe activation",
  "catalogRefresh.progress": "Overall progress: {{percent}}%",
  "catalogRefresh.elapsed": "Elapsed: {{elapsed}}",
  "catalogRefresh.items": "{{completed}} / {{total}} items",
  "catalogRefresh.pages": "{{completed}} / {{total}} pages",
  "catalogRefresh.safeCode": "Safe code: {{code}}",
  "eyebrow.updates": "UPDATES",
  "general.appUpdate": "App update",
  "metric.channel": "Channel",
  "metric.currentVersion": "Current",
  "metric.availableVersion": "Available",
  "value.current": "Current",
  "general.checkUpdate": "Check",
  "general.restart": "Review restart",
  "payments.title": "Payment terminals",
  "payments.subtitle":
    "Only public environment and terminal choices are stored here. Protected payment credentials are managed by the service.",
  "eyebrow.activeCardTerminal": "ACTIVE CARD TERMINAL",
  "payments.provider": "Card terminal provider",
  "payments.providerHint":
    "Select exactly one terminal provider; card payments remain disabled when no available provider is selected.",
  "payments.noneSelected": "Not selected: card payments disabled",
  "payments.squareSelected": "Square selected",
  "payments.linklySelected": "Linkly selected",
  "eyebrow.cardTerminal": "CARD TERMINAL",
  "field.locationId": "Location ID",
  "field.squareLocationId": "Square location ID",
  "field.deviceId": "Device ID",
  "field.squareDeviceId": "Square device ID",
  "square.serverToken": "Server Square access",
  "square.tokenReady": "Configured and enabled",
  "square.tokenDisabled": "Configured but disabled",
  "square.tokenMissing": "Not configured",
  "square.tokenIdle": "Server status not loaded",
  "square.tokenLoading": "Checking server status…",
  "square.tokenFailed": "Could not load server status",
  "square.setupUnavailable": "Square setup service unavailable",
  "square.currentBinding": "Current device binding",
  "square.location": "Location",
  "square.device": "Checkout device",
  "square.loadLocations": "Load locations",
  "square.loadDevices": "Load devices",
  "square.selectLocation": "Choose location",
  "square.selectDevice": "Choose device",
  "square.locationPickerTitle": "Choose a Square location",
  "square.devicePickerTitle": "Choose a Square checkout device",
  "square.locationPickerHint":
    "Select one server location. Its name is shown above the public ID and status.",
  "square.devicePickerHint":
    "Select one enabled checkout device for the chosen location.",
  "square.notSelected": "Not selected",
  "square.notLoaded": "Not loaded yet",
  "square.loadingLocations": "Loading Square locations…",
  "square.loadingDevices": "Loading Square devices…",
  "square.locationsEmpty": "No Square locations were returned.",
  "square.devicesEmpty": "No Square devices were returned for this location.",
  "square.loadFailed": "Could not load Square setup data. Try again.",
  "square.statusUnknown": "Status unavailable",
  "square.closePicker": "Close",
  "square.deviceCode": "Production Device Code",
  "square.deviceCodeName": "Device Code name",
  "square.deviceCodeNameHint":
    "Use a short name that identifies this checkout, then create one code only.",
  "square.loadDeviceCodes": "Load codes",
  "square.createDeviceCode": "Create code",
  "square.refreshDeviceCode": "Refresh current",
  "square.deviceCodesIdle": "Device Codes not loaded yet",
  "square.deviceCodesLoading": "Loading Device Codes…",
  "square.deviceCodesEmpty": "No Device Codes exist for this location.",
  "square.deviceCodePairing":
    "Enter the displayed code on the Square Terminal, complete pairing there, then refresh the current code to confirm its status.",
  "square.deviceCodeSandboxDisabled":
    "Sandbox uses official Square test devices; no Device Code needs to be created or paired.",
  "square.currentDeviceCode": "Current",
  "square.codePending": "Code pending",
  "action.test": "Test",
  "eyebrow.eftpos": "EFTPOS",
  "payments.linklyHint":
    "Handheld POS uses the backend asynchronous Linkly channel; merchant authentication material is not stored here.",
  "linkly.storeCredentials": "Store credentials",
  "linkly.currentPairing": "Current device pairing",
  "linkly.backendReady": "Backend ready",
  "linkly.notAvailable": "Not available",
  "linkly.statusLoading": "Checking…",
  "linkly.statusReady": "Ready",
  "linkly.statusNotReady": "Not ready",
  "linkly.statusPaired": "Paired",
  "linkly.statusUnpaired": "Not paired",
  "linkly.statusUnavailable": "Unavailable",
  "linkly.refresh": "Refresh status",
  "linkly.pairCode": "6-digit Pair Code",
  "linkly.pairCodeHint":
    "Enter the six-digit code shown by the terminal.",
  "linkly.pair": "Pair current terminal",
  "linkly.logonPassed": "Logon test passed",
  "linkly.logonRequired":
    "Pair first, then run a successful logon test before selecting or saving Linkly.",
  "linkly.instructions":
    "On the terminal: FUNC → 8880 → OK / Enter. The Pair Code expires shortly; re-pairing replaces the current terminal binding and creates a new code.",
  "payments.save": "Save payment choices",
  "peripherals.title": "Peripherals",
  "peripherals.subtitle":
    "Discover, connect and verify local printers and scanners.",
  "eyebrow.receipt": "RECEIPT",
  "peripherals.printer": "Printer",
  "peripherals.printing": "Printing",
  "peripherals.drawer": "Drawer",
  "printer.locale.en": "English",
  "printer.locale.zhCN": "Chinese",
  "printer.preferredN160": "Recommended target · printer001",
  "printer.deviceName": "Name",
  "printer.deviceAddress": "Device address",
  "field.peripheralId": "Peripheral ID",
  "field.printerPeripheralId": "Printer peripheral ID",
  "peripherals.scanPrinters": "Scan nearby",
  "action.save": "Save",
  "peripherals.testPrint": "Test",
  "peripherals.testDrawer": "Test drawer",
  "peripherals.clearSavedPrinter": "Clear saved printer",
  "eyebrow.storeProfile": "RECEIPT STORE PROFILE",
  "peripherals.storeProfile": "Receipt store profile",
  "field.receiptBrandName": "Brand name",
  "field.receiptStoreName": "Store name",
  "field.receiptAddress": "Address",
  "field.receiptPhone": "Phone",
  "field.receiptAbn": "ABN",
  "field.receiptReturnPolicy": "Return policy",
  "peripherals.loadStoreProfile": "Load from store",
  "action.connect": "Connect & Save",
  "printer.pickerTitle": "Choose a nearby Bluetooth device",
  "printer.pickerHint":
    "The scan shows every nearby Bluetooth Low Energy device. printer001 is the recommended target for the receipt printer.",
  "printer.scanning": "Scanning for nearby Bluetooth devices…",
  "printer.connecting": "Connecting and saving printer…",
  "printer.noneFound":
    "No nearby Bluetooth devices found. Make sure Bluetooth is on, then scan again.",
  "printer.bluetoothPermissionHint":
    "Allow HB POS to use Bluetooth in device Settings, then return to the app and scan again.",
  "action.openSystemSettings": "Open system settings",
  "eyebrow.scanner": "SCANNER",
  "peripherals.scanner": "Scanner",
  "label.status": "Status: {{status}}",
  "peripherals.captureOneScan": "Capture one scan",
  "device.title": "Device registration",
  "device.subtitle":
    "Changing stores requires a one-time device activation code created for the target store in Web. Queued business records are retained and block the final change.",
  "eyebrow.currentBinding": "CURRENT BINDING",
  "device.currentBinding": "Current",
  "metric.store": "Store",
  "metric.storeName": "Store name",
  "metric.device": "Device",
  "metric.platform": "Platform",
  "metric.expires": "Expires",
  "eyebrow.reregister": "CHANGE STORE",
  "device.reregister": "Change store with activation code",
  "field.deviceActivationCode": "One-time device activation code",
  "field.terminalName": "Terminal name",
  "device.scanActivationCode": "Scan activation code",
  "device.previewActivationCode": "Preview target store",
  "device.currentToTarget": "{{current}} → {{target}}",
  "device.reviewReregistration": "Review device store change",
  "eyebrow.dangerZone": "DANGER ZONE",
  "device.resetRegistration": "Clear device registration",
  "device.resetRegistrationImpact":
    "Stops only this device registration on the server, clears local device and cashier credentials, then returns to registration. Installation ID, synced business data and ordinary settings are retained. Any unfinished local work blocks the action.",
  "device.reviewResetRegistration": "Review clear registration",
  "hardware.title": "Hardware test",
  "hardware.subtitle":
    "Verify each hardware path without creating a sale or payment.",
  "hardware.printTest": "Print test",
  "hardware.captureScan": "Capture scan",
  "eyebrow.lastCapture": "LAST CAPTURE",
  "hardware.lastScan": "Last scan",
  "hardware.waitingForTest": "Waiting for test",
  "confirmation.body":
    "Local pending data is never cleared; any pending work blocks this action.",
  "confirmation.resetDeviceBody":
    "Read the impact above, then scan a real employee barcode with device registration permission. Cached, emergency and cross-store authorization is rejected. The barcode is used once and is not saved.",
  "field.employeeBarcode": "Employee barcode",
  "field.employeeBarcodeHint": "Scan now — no value is prefilled",
  "action.cancel": "Cancel",
  "action.checking": "Checking…",
  "action.confirm": "Confirm",
  "environment.production": "Production",
  "environment.sandbox": "Sandbox",
  "availability.ready": "Runtime ready",
  "availability.unavailable": "Runtime unavailable{{blocker}}",
  "confirmation.changeApiAddress": "Change API address\n{{apiBaseUrl}}",
  "confirmation.changePaymentSettings": "Change payment terminal settings",
  "confirmation.pairLinkly": "Pair the current Linkly terminal",
  "confirmation.resetCatalog": "Reset local catalog",
  "confirmation.reregisterDevice":
    "Change device store\n{{currentStoreCode}} → {{targetStoreName}} ({{targetStoreCode}})\n{{deviceSystem}} · expires {{expiresAt}}",
  "confirmation.resetDeviceRegistration":
    "Clear registration for {{storeCode}} / {{deviceCode}}",
  "confirmation.restartApp": "Restart app safely",
  "hardware.connected": "Connected",
  "hardware.ready": "Ready",
  "hardware.disconnected": "Disconnected",
  "hardware.unavailable": "Unavailable",
  "status.api-address-saved":
    "API address saved. The runtime must reconnect as directed by its adapter.",
  "status.api-health-check-failed":
    "Candidate API unavailable; previous address retained",
  "status.api-health-check-passed":
    "Candidate API is reachable; current address is unchanged",
  "status.app-restart-requested": "Safe restart requested",
  "status.app-update-check-failed": "Update check failed",
  "status.app-update-checked": "Update check complete",
  "status.cash-drawer-test-failed": "Cash drawer test failed",
  "status.cash-drawer-test-passed": "Cash drawer test sent",
  "status.cash-drawer-test-unknown":
    "Cash drawer command sent, but the printer did not confirm the result. Check the drawer manually; the app will not retry automatically.",
  "status.catalog-download-failed":
    "Download failed; current catalog remains active",
  "status.catalog-downloaded": "Catalog activated",
  "status.catalog-reset": "Local catalog reset",
  "status.catalog-reset-failed": "Catalog reset failed",
  "status.device-reregister-failed": "Re-registration did not start",
  "status.device-reregister-started": "Device re-registration started",
  "status.device-activation-preview-failed":
    "Activation code was rejected, expired, or is for another platform",
  "status.device-registration-reset-barcode-required":
    "Scan an authorized employee barcode to continue",
  "status.device-registration-reset-completed":
    "Device registration cleared; restarting registration",
  "status.device-registration-reset-failed":
    "Device registration was not cleared",
  "status.device-registration-reset-pending-recovery":
    "Reset result requires online recovery; POS remains locked",
  "status.invalid-api-address": "Invalid API address",
  "status.invalid-device-registration": "Enter and preview a valid activation code",
  "status.load-failed": "Settings load failed",
  "status.linkly-health-load-failed": "Could not refresh Linkly backend status",
  "status.linkly-pair-code-invalid": "Enter a six-digit numeric Pair Code",
  "status.linkly-pair-failed": "Linkly terminal pairing failed",
  "status.linkly-pair-unknown":
    "Pairing result unknown; status refreshed and no retry was sent",
  "status.linkly-paired": "Linkly terminal paired; status refreshed",
  "status.linkly-setup-required":
    "Linkly backend must be ready and logon test must pass first",
  "status.payment-settings-invalid":
    "Public payment provider configuration is incomplete",
  "status.payment-settings-save-failed": "Payment settings save failed",
  "status.payment-settings-saved": "Payment settings saved",
  "status.payment-test-failed": "Payment test failed",
  "status.payment-test-passed": "Payment provider available",
  "status.pending-local-data": "Pending local work blocked the action",
  "status.permission-required": "Settings permission required",
  "status.printer-connect-failed":
    "Printer connection failed; settings were not saved",
  "status.printer-connected": "Printer connected and saved",
  "status.printer-connected-save-failed":
    "Printer connected, but settings could not be saved",
  "status.printer-clear-failed": "Saved printer could not be cleared",
  "status.printer-cleared": "Saved printer cleared",
  "status.printer-cleared-disconnect-failed":
    "Saved printer cleared, but the device may still be connected",
  "status.printer-bluetooth-authorization-pending":
    "Complete the device Bluetooth permission prompt, then scan again",
  "status.printer-bluetooth-permission-required":
    "Bluetooth permission is required to scan nearby devices",
  "status.printer-bluetooth-powered-off":
    "Bluetooth is off. Turn it on, then scan again",
  "status.printer-bluetooth-restricted":
    "Bluetooth access is restricted by device policy and cannot be changed here",
  "status.printer-scan-failed": "Printer scan failed",
  "status.printer-scan-finished": "Printer scan complete",
  "status.printer-settings-save-failed": "Printer settings save failed",
  "status.printer-settings-saved": "Printer settings saved",
  "status.printer-test-failed": "Test print failed",
  "status.printer-test-unknown":
    "Test command sent, but the printer did not confirm the result. Check the paper manually; the app will not retry automatically.",
  "status.printer-test-passed": "Test receipt sent",
  "status.receipt-profile-loaded": "Loaded. Save to apply.",
  "status.receipt-profile-load-failed": "Could not load store profile.",
  "status.restart-failed": "Restart or endpoint change failed",
  "status.safety-check-failed": "Safety state unavailable; action blocked",
  "status.scanner-test-failed": "Scanner test failed",
  "status.scanner-test-passed": "Scan received",
} as const;

export type SettingsCopyKey = keyof typeof settingsEnglishCopy;

export const settingsChineseCopy = {
  "header.eyebrow": "终端管理",
  "header.title": "设置",
  "header.subtitle":
    "管理公开运行参数与本机外设；支付凭据和设备密钥始终留在受保护服务中。",
  "action.backToSales": "返回销售页",
  "navigation.title": "设置分区",
  "navigation.general": "系统与目录",
  "navigation.payments": "支付终端",
  "navigation.peripherals": "外设",
  "navigation.device": "设备注册",
  "navigation.hardware": "硬件测试",
  "device.currentTerminal": "当前终端",
  "device.unbound": "未绑定",
  "state.loading": "正在读取本机设置…",
  "state.failed": "本机设置暂不可读",
  "state.unauthorized": "没有查看设置权限",
  "unavailable.eyebrow": "终端设置",
  "unavailable.title": "设置服务暂不可用",
  "unavailable.hint":
    "本机运行时尚未接入设置适配器，未执行任何配置或数据变更。",
  "general.title": "系统与商品目录",
  "general.subtitle":
    "切换服务地址会改变数据分区，必须确认且本机无待处理交易。",
  "general.terminalPreferences": "交易、语言与安全",
  "general.language": "语言",
  "general.switchLanguage": "English",
  "general.singleScreen": "手持终端采用单屏操作，不提供第二屏设置。",
  "general.securityHint":
    "交易访问继续受收银员权限范围和自动锁定策略保护。",
  "eyebrow.interaction": "交互反馈",
  "general.soundFeedback": "音效反馈",
  "general.buttonSound": "普通按钮音效",
  "general.buttonSoundHint":
    "覆盖按钮、按键、页面导航和危险操作；开启时播放一次示例，关闭后保持静音。",
  "general.specialNodeSound": "特殊节点音效",
  "general.specialNodeSoundHint":
    "覆盖商品查询、加购/累加、未找到和受阻结果；开启时播放一次示例，关闭后保持静音。",
  "eyebrow.network": "网络",
  "general.apiAddress": "API 地址",
  "general.useLocalApi": "本地后端",
  "general.useRemoteApi": "远程后端",
  "general.testApiAddress": "测试连接",
  "general.reviewApiAddress": "检查并申请切换",
  "eyebrow.catalog": "目录",
  "general.catalog": "商品目录",
  "metric.snapshot": "快照",
  "metric.items": "商品数",
  "metric.activated": "启用时间",
  "value.none": "无",
  "general.downloadCatalog": "下载并安全启用",
  "general.downloadingCatalog": "正在刷新…",
  "general.resetCatalog": "申请重置",
  "general.catalogSafety":
    "下载失败时保留当前已验证目录；重置前不会清除待同步销售或退款。",
  "general.catalogBackground":
    "可离开本页，目录会在应用内继续刷新；返回后仍显示相同进度。",
  "catalogRefresh.running": "正在刷新目录",
  "catalogRefresh.success": "目录已在后台完成并启用",
  "catalogRefresh.warning": "目录已启用，但有安全警告",
  "catalogRefresh.failed": "目录刷新未完成，旧目录仍可用",
  "catalogRefresh.preparing": "正在等待目录准备",
  "catalogRefresh.currentStep": "当前步骤：{{step}}",
  "catalogRefresh.step.prepare": "准备目录",
  "catalogRefresh.step.products": "下载并校验商品",
  "catalogRefresh.step.promotions": "同步促销",
  "catalogRefresh.step.activate": "安全激活",
  "catalogRefresh.progress": "总进度：{{percent}}%",
  "catalogRefresh.elapsed": "已用时：{{elapsed}}",
  "catalogRefresh.items": "{{completed}} / {{total}} 件商品",
  "catalogRefresh.pages": "{{completed}} / {{total}} 页",
  "catalogRefresh.safeCode": "安全码：{{code}}",
  "eyebrow.updates": "更新",
  "general.appUpdate": "应用更新",
  "metric.channel": "渠道",
  "metric.currentVersion": "当前版本",
  "metric.availableVersion": "可用版本",
  "value.current": "已是最新",
  "general.checkUpdate": "检查更新",
  "general.restart": "申请安全重启",
  "payments.title": "支付终端",
  "payments.subtitle":
    "这里只保存公开的环境、门店和终端选择；受保护支付凭据由服务端管理。",
  "eyebrow.activeCardTerminal": "当前刷卡终端",
  "payments.provider": "刷卡终端提供方",
  "payments.providerHint":
    "必须明确选择一个终端提供方；未选择或所选终端不可用时，银行卡支付保持关闭。",
  "payments.noneSelected": "未选择：银行卡支付已关闭",
  "payments.squareSelected": "已选择 Square",
  "payments.linklySelected": "已选择 Linkly",
  "eyebrow.cardTerminal": "刷卡终端",
  "field.locationId": "门店位置 ID",
  "field.squareLocationId": "Square 门店位置 ID",
  "field.deviceId": "终端设备 ID",
  "field.squareDeviceId": "Square 终端设备 ID",
  "square.serverToken": "服务端 Square 授权",
  "square.tokenReady": "已配置且已启用",
  "square.tokenDisabled": "已配置但已停用",
  "square.tokenMissing": "尚未配置",
  "square.tokenIdle": "尚未加载服务端状态",
  "square.tokenLoading": "正在检查服务端状态…",
  "square.tokenFailed": "无法加载服务端状态",
  "square.setupUnavailable": "Square 设置服务不可用",
  "square.currentBinding": "本机当前绑定",
  "square.location": "门店位置",
  "square.device": "收银终端",
  "square.loadLocations": "加载位置",
  "square.loadDevices": "加载终端",
  "square.selectLocation": "选择位置",
  "square.selectDevice": "选择终端",
  "square.locationPickerTitle": "选择 Square 门店位置",
  "square.devicePickerTitle": "选择 Square 收银终端",
  "square.locationPickerHint": "从服务端位置中选择一项；主行显示名称，次行显示公开 ID 与状态。",
  "square.devicePickerHint": "为当前门店位置选择一台已启用的收银终端。",
  "square.notSelected": "尚未选择",
  "square.notLoaded": "尚未加载",
  "square.loadingLocations": "正在加载 Square 门店位置…",
  "square.loadingDevices": "正在加载 Square 终端…",
  "square.locationsEmpty": "服务端未返回 Square 门店位置。",
  "square.devicesEmpty": "当前门店位置没有可用的 Square 终端。",
  "square.loadFailed": "无法加载 Square 设置，请重试。",
  "square.statusUnknown": "状态未知",
  "square.closePicker": "关闭",
  "square.deviceCode": "Production Device Code",
  "square.deviceCodeName": "配对码名称",
  "square.deviceCodeNameHint": "使用可识别当前收银台的简短名称；每次只创建一个配对码。",
  "square.loadDeviceCodes": "加载配对码",
  "square.createDeviceCode": "创建配对码",
  "square.refreshDeviceCode": "刷新当前状态",
  "square.deviceCodesIdle": "尚未加载配对码",
  "square.deviceCodesLoading": "正在加载 Device Code…",
  "square.deviceCodesEmpty": "当前门店位置尚无 Device Code。",
  "square.deviceCodePairing":
    "在 Square Terminal 上输入显示的配对码并完成配对，然后手动刷新当前状态确认结果。",
  "square.deviceCodeSandboxDisabled":
    "Sandbox 使用 Square 官方测试终端，无需创建或配对 Device Code。",
  "square.currentDeviceCode": "当前",
  "square.codePending": "等待生成配对码",
  "action.test": "测试可用性",
  "eyebrow.eftpos": "刷卡终端",
  "payments.linklyHint":
    "手持 POS 使用后端异步 Linkly 通道。商户与 POS 认证材料不会进入本机普通设置。",
  "linkly.storeCredentials": "门店云端凭据",
  "linkly.currentPairing": "当前设备配对",
  "linkly.backendReady": "后端就绪",
  "linkly.notAvailable": "不可用",
  "linkly.statusLoading": "正在检查…",
  "linkly.statusReady": "就绪",
  "linkly.statusNotReady": "未就绪",
  "linkly.statusPaired": "已配对",
  "linkly.statusUnpaired": "未配对",
  "linkly.statusUnavailable": "不可用",
  "linkly.refresh": "刷新状态",
  "linkly.pairCode": "6 位配对码",
  "linkly.pairCodeHint": "输入终端显示的六位数字配对码。",
  "linkly.pair": "配对当前终端",
  "linkly.logonPassed": "登录测试已通过",
  "linkly.logonRequired":
    "请先配对，再通过登录测试，之后才能选择或保存 Linkly。",
  "linkly.instructions":
    "在终端上操作：FUNC → 8880 → OK / Enter。配对码短时有效会过期；重新配对会替换当前终端绑定并生成新码。",
  "payments.save": "保存支付终端选择",
  "peripherals.title": "外设",
  "peripherals.subtitle": "发现、连接并验证本机打印机、钱箱与扫描器。",
  "eyebrow.receipt": "小票",
  "peripherals.printer": "小票打印机",
  "peripherals.printing": "打印",
  "peripherals.drawer": "钱箱",
  "printer.locale.en": "英文",
  "printer.locale.zhCN": "中文",
  "printer.preferredN160": "推荐目标",
  "printer.deviceName": "名称",
  "printer.deviceAddress": "设备地址",
  "field.peripheralId": "设备 ID",
  "field.printerPeripheralId": "打印机设备 ID",
  "peripherals.scanPrinters": "扫描附近设备",
  "action.save": "保存",
  "peripherals.testPrint": "测试打印",
  "peripherals.testDrawer": "测试钱箱",
  "peripherals.clearSavedPrinter": "清除已保存打印机",
  "eyebrow.storeProfile": "小票门店资料",
  "peripherals.storeProfile": "小票门店资料",
  "field.receiptBrandName": "品牌名称",
  "field.receiptStoreName": "门店名称",
  "field.receiptAddress": "地址",
  "field.receiptPhone": "电话",
  "field.receiptAbn": "ABN",
  "field.receiptReturnPolicy": "退货政策",
  "peripherals.loadStoreProfile": "从门店载入",
  "action.connect": "连接并保存",
  "printer.pickerTitle": "选择附近的蓝牙设备",
  "printer.pickerHint":
    "扫描结果会显示附近所有低功耗蓝牙设备；printer001 是推荐目标。",
  "printer.scanning": "正在扫描附近的蓝牙设备…",
  "printer.connecting": "正在连接并保存打印机…",
  "printer.noneFound":
    "未发现附近的蓝牙设备。请确认蓝牙已开启，然后重新扫描。",
  "printer.bluetoothPermissionHint":
    "请在设备系统设置中允许 HB POS 使用蓝牙，然后返回应用重新扫描。",
  "action.openSystemSettings": "前往系统设置",
  "eyebrow.scanner": "扫描器",
  "peripherals.scanner": "扫描器",
  "label.status": "状态：{{status}}",
  "peripherals.captureOneScan": "等待一次扫码",
  "device.title": "设备注册",
  "device.subtitle": "更换分店需要 Web 端为目标分店创建的一次性设备开通码。本地待处理记录会保留，并阻止最终换店。",
  "eyebrow.currentBinding": "当前绑定",
  "device.currentBinding": "当前绑定",
  "metric.store": "门店",
  "metric.storeName": "门店名称",
  "metric.device": "设备",
  "metric.platform": "平台",
  "metric.expires": "到期时间",
  "eyebrow.reregister": "设备换店",
  "device.reregister": "使用开通码更换分店",
  "field.deviceActivationCode": "一次性设备开通码",
  "field.terminalName": "终端名称",
  "device.scanActivationCode": "扫描设备开通码",
  "device.previewActivationCode": "预览目标分店",
  "device.currentToTarget": "{{current}} → {{target}}",
  "device.reviewReregistration": "检查并确认设备换店",
  "eyebrow.dangerZone": "危险操作",
  "device.resetRegistration": "清除设备注册",
  "device.resetRegistrationImpact":
    "仅在服务端停用当前设备记录，并清除本机设备及员工凭据，然后返回注册页。installation ID、已同步业务数据和普通设置会保留；存在任何未完成本地数据时操作会被阻断。",
  "device.reviewResetRegistration": "阅读影响并继续",
  "hardware.title": "硬件测试",
  "hardware.subtitle": "逐项验证硬件链路；测试不会创建销售或支付。",
  "hardware.printTest": "打印测试小票",
  "hardware.captureScan": "等待一次扫码",
  "eyebrow.lastCapture": "最近扫码",
  "hardware.lastScan": "最近扫码",
  "hardware.waitingForTest": "等待测试",
  "confirmation.body":
    "确认前会再次检查活动购物车、待同步销售或退款、未决支付与耐久写入。待同步数据不会被清除；存在任何项目时操作会被阻断。",
  "confirmation.resetDeviceBody":
    "阅读影响说明后，请重新扫描具备设备注册权限的真实员工条码。离线缓存、紧急登录及跨店授权均会被拒绝；条码仅使用一次且不会保存。",
  "field.employeeBarcode": "员工条码",
  "field.employeeBarcodeHint": "请现在扫码，不会预填任何条码",
  "action.cancel": "取消",
  "action.checking": "检查中…",
  "action.confirm": "确认执行",
  "environment.production": "生产",
  "environment.sandbox": "沙盒",
  "availability.ready": "运行时可用",
  "availability.unavailable": "运行时未配置{{blocker}}",
  "confirmation.changeApiAddress": "切换 API 地址\n{{apiBaseUrl}}",
  "confirmation.changePaymentSettings": "切换支付终端配置",
  "confirmation.pairLinkly": "配对当前 Linkly 终端",
  "confirmation.resetCatalog": "重置本地商品目录",
  "confirmation.reregisterDevice":
    "更换设备分店\n{{currentStoreCode}} → {{targetStoreName}}（{{targetStoreCode}}）\n{{deviceSystem}} · {{expiresAt}} 到期",
  "confirmation.resetDeviceRegistration":
    "清除 {{storeCode}} / {{deviceCode}} 的设备注册",
  "confirmation.restartApp": "安全重启应用",
  "hardware.connected": "已连接",
  "hardware.ready": "就绪",
  "hardware.disconnected": "未连接",
  "hardware.unavailable": "不可用",
  "status.api-address-saved":
    "API 地址已保存；运行时必须按适配器指引重新建立。",
  "status.api-health-check-failed": "候选 API 健康检查失败，旧地址保持不变",
  "status.api-health-check-passed": "候选 API 连接成功，当前地址尚未切换",
  "status.app-restart-requested": "已请求安全重启",
  "status.app-update-check-failed": "更新检查失败",
  "status.app-update-checked": "更新检查完成",
  "status.cash-drawer-test-failed": "钱箱测试失败",
  "status.cash-drawer-test-passed": "钱箱测试指令已发送",
  "status.cash-drawer-test-unknown":
    "钱箱指令已发送，但打印机未确认结果；请人工检查钱箱，应用不会自动重试。",
  "status.catalog-download-failed": "目录下载失败，当前目录仍可用",
  "status.catalog-downloaded": "目录已下载并启用",
  "status.catalog-reset": "本地目录已重置",
  "status.catalog-reset-failed": "目录重置失败",
  "status.device-reregister-failed": "重新注册未开始",
  "status.device-reregister-started": "设备重新注册已开始",
  "status.device-activation-preview-failed": "开通码已被拒绝、已过期或不属于当前平台",
  "status.device-registration-reset-barcode-required":
    "请扫描具备权限的员工条码后继续",
  "status.device-registration-reset-completed":
    "设备注册已清除，正在返回注册流程",
  "status.device-registration-reset-failed": "设备注册未清除",
  "status.device-registration-reset-pending-recovery":
    "重置结果需要联网恢复，POS 将保持锁定",
  "status.invalid-api-address": "API 地址格式不安全",
  "status.invalid-device-registration": "请输入并预览有效的设备开通码",
  "status.load-failed": "读取设置失败",
  "status.linkly-health-load-failed": "无法刷新 Linkly 后端状态",
  "status.linkly-pair-code-invalid": "请输入六位数字配对码",
  "status.linkly-pair-failed": "Linkly 终端配对失败",
  "status.linkly-pair-unknown":
    "配对结果未知；已刷新状态，且未自动重试",
  "status.linkly-paired": "Linkly 终端已配对；状态已刷新",
  "status.linkly-setup-required":
    "Linkly 后端必须先就绪且登录测试通过",
  "status.payment-settings-invalid": "可用支付通道的公开配置不完整",
  "status.payment-settings-save-failed": "支付终端设置保存失败",
  "status.payment-settings-saved": "支付终端设置已保存",
  "status.payment-test-failed": "支付通道测试失败",
  "status.payment-test-passed": "支付通道可用",
  "status.pending-local-data": "存在本地待处理业务，操作已阻断且数据保持不变",
  "status.permission-required": "需要相应设置权限",
  "status.printer-connect-failed": "打印机连接失败，设置未保存",
  "status.printer-connected": "打印机已连接并保存",
  "status.printer-connected-save-failed": "打印机已连接，但设置保存失败",
  "status.printer-clear-failed": "未能清除已保存的打印机",
  "status.printer-cleared": "已清除保存的打印机",
  "status.printer-cleared-disconnect-failed":
    "已清除保存的打印机，但设备可能仍保持连接",
  "status.printer-bluetooth-authorization-pending":
    "请先完成设备蓝牙授权弹窗，然后重新扫描",
  "status.printer-bluetooth-permission-required":
    "扫描附近设备需要蓝牙权限",
  "status.printer-bluetooth-powered-off": "蓝牙已关闭，请开启后重新扫描",
  "status.printer-bluetooth-restricted":
    "蓝牙访问受到设备系统策略限制，无法在此解除",
  "status.printer-scan-failed": "打印机扫描失败",
  "status.printer-scan-finished": "打印机扫描完成",
  "status.printer-settings-save-failed": "打印机设置保存失败",
  "status.printer-settings-saved": "打印机设置已保存",
  "status.printer-test-failed": "测试打印失败",
  "status.printer-test-unknown":
    "测试命令已发送，但打印机未确认结果；请人工检查是否出纸，应用不会自动重试。",
  "status.printer-test-passed": "测试小票已发送",
  "status.receipt-profile-loaded": "已载入，保存后生效",
  "status.receipt-profile-load-failed": "门店资料载入失败",
  "status.restart-failed": "重启或地址切换失败",
  "status.safety-check-failed": "无法确认本地安全状态，操作已阻断",
  "status.scanner-test-failed": "扫码测试失败",
  "status.scanner-test-passed": "已收到扫码",
} as const satisfies Record<SettingsCopyKey, string>;

const settingsCopy = {
  en: settingsEnglishCopy,
  zh: settingsChineseCopy,
} as const;

export type SettingsLocale = keyof typeof settingsCopy;

export function resolveSettingsLocale(language?: string): SettingsLocale {
  return language?.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function settingsText(
  locale: SettingsLocale,
  key: SettingsCopyKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  const template = settingsCopy[locale][key];
  if (!values) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name: string) => {
    const value = values[name];
    return value === undefined ? placeholder : String(value);
  });
}
