export const heldOrdersEnglishCopy = {
  title: "Held sales",
  subtitle: "Durable local holds for this terminal only.",
  "subtitle.shared": "This device and other devices are shown in separate sections.",
  "action.back": "Back to sales",
  "action.refresh": "Refresh",
  "action.hold": "Hold current sale",
  "action.recall": "Recall sale",
  "action.take-remote": "Take on this terminal",
  "action.recover": "Recover sale",
  "action.release": "Return to pending",
  "action.details": "View details",
  "action.backToList": "Back to held sales",
  "action.force-release": "Force release",
  "action.delete": "Delete",
  "action.share": "Share",
  "filter.today": "Today",
  "filter.all": "All",
  "filter.local": "This device",
  "filter.other": "Other devices",
  "list.title": "Pending holds",
  "list.sequence": "Local #{{sequence}}",
  "list.items": "{{count}} items",
  "list.amount": "Amount",
  "list.heldAt": "Held {{time}}",
  "detail.title": "Held sale details",
  "detail.hint": "Review this held sale before changing its durable state.",
  "remote.source": "Device {{device}} · {{cashier}}",
  "status.Pending": "Ready to recall",
  "status.Recalling": "Recall needs recovery",
  "status.local-pending": "Ready to recall",
  "status.claiming-here": "Restoring on this terminal",
  "status.local-pending-publish": "Awaiting share",
  "status.published-shareable": "Shared",
  "status.remote-pending": "Remote · available",
  "status.blocked": "Cannot share",
  "blocked.LEGACY_PAYLOAD_CORRUPTED": "Legacy hold data could not be read losslessly.",
  "blocked.LEGACY_PAYLOAD_VERSION_UNSUPPORTED": "Legacy hold version is not supported.",
  "blocked.SHARED_CART_VERSION_UNSUPPORTED": "Hold cart version is not supported.",
  "blocked.SHARED_CART_MODE_NOT_SALE": "Only ordinary sale carts can be shared.",
  "blocked.SHARED_CART_LINE_KIND_NOT_SALE": "A returned or special line prevents sharing.",
  "blocked.SHARED_CART_RETURN_ORIGINAL_NOT_EMPTY": "Return reference data prevents sharing.",
  "blocked.SHARED_CART_INVALID": "Hold cart data could not be migrated losslessly.",
  "blocked.LOCAL_DELETE_PENDING": "Deletion is incomplete. Retry when online.",
  "blocked.SHARED_HELD_ORDER_CANCELLED": "The remote hold is cancelled. You can delete this local record safely.",
  "blocked.unknown": "This hold cannot be shared safely.",
  "empty.title": "No held sales on this terminal",
  "empty.hint": "Holds are local to this store and device.",
  "empty.hint.shared": "Holds from other terminals in this store appear here.",
  "empty.other.title": "No held sales from other devices",
  "empty.other.hint": "Other devices in this store appear here after background refresh.",
  "loading": "Loading held sales…",
  "unauthorized.title": "Recall access is not available",
  "unauthorized.hint": "Ask a supervisor if you need to recall a sale.",
  "failed.title": "Held sales could not be loaded",
  "failed.hint": "The encrypted ledger was not changed. Try again when ready.",
  "error.shared-sync": "Shared held sales could not be refreshed; local rows are still shown.",
  "forceRelease.title": "Force release held sale",
  "forceRelease.reasonAccessibility": "Force release reason (required)",
  "forceRelease.reasonPlaceholder": "Required: why is this release needed?",
  "forceRelease.confirm": "Confirm force release",
  "delete.title": "Delete held sale?",
  "delete.hint": "This permanently removes the local hold. A shared hold is cancelled online first.",
  "delete.cancel": "Keep held sale",
  "delete.confirm": "Delete held sale",
  "result.held": "Sale held locally.",
  "result.recalled": "Held sale restored.",
  "result.recovered": "Held sale restored after recovery.",
  "result.released": "The recovered sale was returned to pending.",
  "result.deleted": "Held sale deleted.",
  "result.authorization-denied": "This action is not authorized.",
  "result.sale-mode-required": "Only sale carts can be held or recalled.",
  "result.cart-empty": "Add an item before holding this sale.",
  "result.cart-not-empty": "Finish or clear the current sale before recalling.",
  "result.operation-in-progress": "Another hold action is still in progress.",
  "result.hold-failed": "The sale was not held.",
  "result.hold-committed-cart-not-cleared": "The sale was held; verify the cart before continuing.",
  "result.hold-fence-not-cleared": "The sale was held and the terminal remains blocked until cart recovery completes.",
  "result.terminal-fence-blocked": "Finish the active held-sale recovery before continuing.",
  "result.claim-failed": "This hold is no longer available to recall.",
  "result.restore-failed": "The hold was released without restoring the cart.",
  "result.complete-failed": "The hold was released without restoring the cart.",
  "result.rollback-failed": "Recall needs supervisor recovery before continuing.",
  "result.release-failed": "Recall remains in recovery. Use Recover hold explicitly.",
  "result.delete-failed": "The held sale was not deleted.",
  "result.delete-shared-failed": "Online cancellation failed. The local hold remains blocked; retry when online.",
  "result.load-failed": "Held sales could not be loaded.",
  "result.shared-prepared-awaiting-activation": "The claim is prepared on the server; finish activation to restore.",
  "result.shared-fence-held": "Another held-sale action is active on this terminal.",
  "result.shared-restore-failed": "Cart restore failed; the active shared claim was kept. Use Recover sale before continuing.",
  "result.shared-conflict": "The remote hold changed; refresh and try again.",
  "result.shared-not-available": "Shared held sales are not available on this terminal.",
  "result.force-released": "The held sale was force released.",
  "result.force-release-failed": "Force release failed; the claim was not changed.",
  "result.force-release-unavailable": "Force release is not configured on this terminal.",
  "result.force-release-reason-required": "A reason is required to force release.",
} as const;

export type HeldOrdersCopyKey = keyof typeof heldOrdersEnglishCopy;

const heldOrdersChineseCopy = {
  title: "挂单",
  subtitle: "仅限本门店、本终端的耐久本地挂单。",
  "subtitle.shared": "本机与其他设备挂单分栏显示。",
  "action.back": "返回收银",
  "action.refresh": "刷新",
  "action.hold": "挂起当前销售",
  "action.recall": "取回销售",
  "action.take-remote": "本机在线取单",
  "action.recover": "恢复取单",
  "action.release": "退回待取",
  "action.details": "查看详情",
  "action.backToList": "返回挂单列表",
  "action.force-release": "强制释放",
  "action.delete": "删除",
  "action.share": "共享",
  "filter.today": "今天",
  "filter.all": "全部",
  "filter.local": "本机",
  "filter.other": "其他设备",
  "list.title": "待取挂单",
  "list.sequence": "本地序号 #{{sequence}}",
  "list.items": "{{count}} 件",
  "list.amount": "金额",
  "list.heldAt": "挂单于 {{time}}",
  "detail.title": "挂单详情",
  "detail.hint": "更改耐久状态前，请核对这条挂单。",
  "remote.source": "设备 {{device}} · {{cashier}}",
  "status.Pending": "可取回",
  "status.Recalling": "需要恢复",
  "status.local-pending": "可取回",
  "status.claiming-here": "正在本机取单/恢复",
  "status.local-pending-publish": "待共享",
  "status.published-shareable": "已共享",
  "status.remote-pending": "远端 · 可取",
  "status.blocked": "无法共享",
  "blocked.LEGACY_PAYLOAD_CORRUPTED": "旧挂单数据无法无损读取。",
  "blocked.LEGACY_PAYLOAD_VERSION_UNSUPPORTED": "旧挂单版本不受支持。",
  "blocked.SHARED_CART_VERSION_UNSUPPORTED": "挂单购物车版本不受支持。",
  "blocked.SHARED_CART_MODE_NOT_SALE": "仅普通销售购物车可共享。",
  "blocked.SHARED_CART_LINE_KIND_NOT_SALE": "存在退货或特殊行，无法共享。",
  "blocked.SHARED_CART_RETURN_ORIGINAL_NOT_EMPTY": "存在退货来源信息，无法共享。",
  "blocked.SHARED_CART_INVALID": "挂单数据无法无损迁移。",
  "blocked.LOCAL_DELETE_PENDING": "删除尚未完成，请联网后重试。",
  "blocked.SHARED_HELD_ORDER_CANCELLED": "远端挂单已取消，可安全删除这条本地记录。",
  "blocked.unknown": "此挂单无法安全共享。",
  "empty.title": "此终端没有挂单",
  "empty.hint": "挂单仅属于当前门店和设备。",
  "empty.hint.shared": "本店其他终端的挂单也会显示在这里。",
  "empty.other.title": "没有非本机挂单",
  "empty.other.hint": "后台刷新后，本店其他设备的挂单会显示在这里。",
  loading: "正在读取挂单…",
  "unauthorized.title": "无取单权限",
  "unauthorized.hint": "如需取回销售，请联系主管。",
  "failed.title": "无法读取挂单",
  "failed.hint": "加密账本未被修改，可稍后重试。",
  "error.shared-sync": "共享挂单刷新失败，仍显示本地挂单。",
  "forceRelease.title": "强制释放挂单",
  "forceRelease.reasonAccessibility": "强制释放原因（必填）",
  "forceRelease.reasonPlaceholder": "必填：为什么需要释放？",
  "forceRelease.confirm": "确认强制释放",
  "delete.title": "删除此挂单？",
  "delete.hint": "删除后无法恢复；已共享挂单会先在线取消，再删除本地记录。",
  "delete.cancel": "保留挂单",
  "delete.confirm": "确认删除",
  "result.held": "销售已本地挂单。",
  "result.recalled": "已恢复挂单销售。",
  "result.recovered": "已恢复挂单销售。",
  "result.released": "已将恢复中的销售退回待取。",
  "result.deleted": "挂单已删除。",
  "result.authorization-denied": "当前操作未获授权。",
  "result.sale-mode-required": "仅销售购物车可挂单或取单。",
  "result.cart-empty": "请先添加商品再挂单。",
  "result.cart-not-empty": "请先完成或清空当前销售再取单。",
  "result.operation-in-progress": "另一个挂单操作仍在进行。",
  "result.hold-failed": "销售未挂单。",
  "result.hold-committed-cart-not-cleared": "销售已挂单，请确认购物车后再继续。",
  "result.hold-fence-not-cleared": "销售已挂单，完成购物车恢复前此终端保持交易锁定。",
  "result.terminal-fence-blocked": "请先完成当前挂单恢复流程。",
  "result.claim-failed": "此挂单已无法取回。",
  "result.restore-failed": "挂单已释放，但未恢复购物车。",
  "result.complete-failed": "挂单已释放，但未恢复购物车。",
  "result.rollback-failed": "取单需要主管恢复后才能继续。",
  "result.release-failed": "取单仍在恢复状态，请明确点击恢复挂单。",
  "result.delete-failed": "挂单未删除。",
  "result.delete-shared-failed": "在线取消失败，本地挂单已阻断发布；联网后可重试删除。",
  "result.load-failed": "无法读取挂单。",
  "result.shared-prepared-awaiting-activation": "服务端已准备取单声明，请完成激活后恢复。",
  "result.shared-fence-held": "本终端已有另一个挂单操作在进行。",
  "result.shared-restore-failed": "购物车恢复失败，共享取单声明仍保持活动；请先执行“恢复取单”。",
  "result.shared-conflict": "远端挂单已变化，请刷新后重试。",
  "result.shared-not-available": "本终端未启用共享挂单。",
  "result.force-released": "挂单已强制释放。",
  "result.force-release-failed": "强制释放失败，取单声明未被修改。",
  "result.force-release-unavailable": "本终端未配置强制释放。",
  "result.force-release-reason-required": "强制释放必须填写原因。",
} as const satisfies Record<HeldOrdersCopyKey, string>;

const heldOrdersCopy = { en: heldOrdersEnglishCopy, zh: heldOrdersChineseCopy } as const;

export type HeldOrdersLocale = keyof typeof heldOrdersCopy;

export function resolveHeldOrdersLocale(language?: string): HeldOrdersLocale {
  return language?.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function heldOrdersText(
  locale: HeldOrdersLocale,
  key: HeldOrdersCopyKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  const template = heldOrdersCopy[locale][key];
  if (!values) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name: string) => {
    const value = values[name];
    return value === undefined ? placeholder : String(value);
  });
}
