import { readFileSync } from 'node:fs'
import { join } from 'node:path'

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message)
}

const root = join(process.cwd(), 'src/pages/ExecutiveSalesIntelligence')
const pageSource = readFileSync(join(root, 'WarehouseProductFlowAnalysis/index.tsx'), 'utf8')
const styleSource = readFileSync(join(root, 'WarehouseProductFlowAnalysis/index.module.css'), 'utf8')
const imageSource = readFileSync(join(root, 'ProductFlowShared/ProductImage.tsx'), 'utf8')
const chartSource = readFileSync(join(root, 'ProductFlowShared/FlowTrendChart.tsx'), 'utf8')

assert(pageSource.includes('buildWarehouseProductFlowDefaultPeriods'), '默认日期必须由 Brisbane 日期 helper 生成')
assert(pageSource.includes('货柜进货') && pageSource.includes('分店订货') && pageSource.includes('已发分店') && pageSource.includes('分店净销量'), '顶部必须展示四阶段流转')
assert(pageSource.includes('getCategoryTree'), '分类筛选必须只读复用现有分类树服务')
assert(pageSource.includes('createLatestRequestGuard'), '请求竞态必须只读复用共享 latestRequestGuard')
assert(pageSource.includes('selectFirstCandidate'), '首次候选响应必须显式选中第一项')
assert(pageSource.includes('全选筛选结果') && pageSource.includes('清空选择'), '左栏必须提供全选和清空选择')
assert(pageSource.includes("product.categoryName || '未分类'") && pageSource.includes("product.supplierName || '国内供应商未映射'"), '左栏商品必须显示分类和国内供应商')
assert(pageSource.includes('商品编码') && pageSource.includes('条码'), '左栏商品必须显示商品编码与条码')
assert(!pageSource.includes('product.metrics.'), '左栏商品主档不得显示区间指标')
assert(pageSource.includes('queryWarehouseProductFlowCandidates'), '左栏候选必须调用独立 candidates 服务')
assert(pageSource.includes('queryWarehouseProductFlowSummary'), '已选汇总必须调用独立 summary 服务')
assert(pageSource.includes('summary?.totals ?? emptyMetrics()'), '顶部四阶段必须只使用已选汇总 totals')
assert(pageSource.includes('getWarehouseProductFlowOptions'), '国内供应商必须从 options 服务加载')
assert((pageSource.match(/showSearch filterOption=\{false\}/g) || []).length >= 2, '分类和国内供应商必须使用本地可搜索 Select')
assert(pageSource.includes('filterWarehouseProductFlowCategoryOptions') && pageSource.includes('filterWarehouseProductFlowSupplierOptions'), '分类和供应商搜索必须复用纯本地筛选逻辑')
assert(pageSource.includes('getWarehouseProductFlowOptions(undefined, undefined, optionsRefreshVersion > 0)') && !pageSource.includes('getWarehouseProductFlowOptions(filter)'), 'supplier options 只能在初始化和刷新全部时请求，并在刷新时绕过缓存')
assert(pageSource.includes('optionsRefreshVersion') && pageSource.includes('setOptionsRefreshVersion((value) => value + 1)'), '刷新全部必须显式重新获取分类和 supplier options')
assert(!pageSource.includes('sortWarehouseProductCandidates'), '候选当前页必须保留服务端稳定分页顺序')
assert((pageSource.match(/onOpenChange=\{\(open\) => \{ if \(!open\) set(?:Category|Supplier)SearchText\(''\) \}\}/g) || []).length === 2, '关闭下拉后必须恢复完整选项并保留已选值')
assert(pageSource.includes('queryWarehouseProductFlowContainers') && pageSource.includes('queryWarehouseProductFlowOrders') && pageSource.includes('queryWarehouseProductFlowShipments'), '三页签必须使用独立明细端点')
assert(pageSource.includes('className={styles.branchButton}') && !pageSource.includes('onClick: () => setBranchCode'), '分店钻取必须提供键盘可聚焦按钮')
assert(pageSource.includes('branchDailyGuard.current.invalidate()') && pageSource.includes('setBranchCode(null)'), '切换当前商品必须清空旧分店趋势')
assert(!pageSource.includes('queryWarehouseProductFlowDetails'), '不得调用通用 details 端点')
assert((pageSource.match(/RangePicker/g) || []).length >= 3, '三套日期范围必须分别提供控件')
assert(pageSource.includes('containerRange') && pageSource.includes('orderShipmentRange') && pageSource.includes('salesRange'), '三套日期状态必须相互独立')
assert(pageSource.includes("applyPeriod('containerPeriod'") && pageSource.includes("applyPeriod('orderShipmentPeriod'") && pageSource.includes("applyPeriod('salesPeriod'"), '三套日期必须分别提交查询')
assert((pageSource.match(/恢复默认/g) || []).length >= 2 && pageSource.includes('restoreActiveDetail'), '业务日期区块必须提供恢复默认操作')
assert(pageSource.includes('queryWarehouseProductFlowDaily') && pageSource.includes('货柜进货趋势'), '货柜趋势必须使用独立 product-daily 接口')
assert(pageSource.includes('orderedQuantity') && pageSource.includes('shippedQuantity'), '订货与发货趋势必须使用独立的每日字段')
assert(pageSource.includes('销售日趋势'), '销售趋势必须独立展示')
assert(pageSource.includes('period={periods.containerPeriod}') && pageSource.includes('period={periods.orderShipmentPeriod}') && pageSource.includes('period={periods.salesPeriod}'), '四阶段指标必须标注各自统计期间')
assert(pageSource.includes('disabledDate'), '日期选择必须限制为 Brisbane 昨天')
assert(pageSource.includes('forceRefreshPending') && pageSource.includes('consumeForceRefresh'), '刷新必须按单次请求消费 forceRefresh')
assert(!pageSource.includes('forceRefresh: refreshVersion > 0'), '刷新后后续普通请求不得永久 forceRefresh')
assert(!/统计状态|统计水位|对账/.test(pageSource), '页面不得展示统计状态、水位或对账消息')
assert(styleSource.includes('grid-template-columns: minmax(280px, 29fr) minmax(420px, 43fr) minmax(300px, 28fr)'), '1366px 必须保持 29/43/28 三栏布局')
assert(styleSource.includes('@media (max-width: 1199px)'), '1024px 必须将右栏下移')
assert(styleSource.includes('@media (max-width: 768px)'), '移动端必须切换单栏')
assert(imageSource.includes('loading="lazy"'), '商品图必须延迟加载')
assert(imageSource.includes('onError'), '商品图必须具有失败回退')
assert(imageSource.includes('48') && imageSource.includes('64'), '商品图必须支持 48/64 缩略图')
assert((chartSource.match(/tabIndex=\{0\}/g) || []).length === 1, '共享图表 SVG 只能有一个 Tab 焦点')
assert(!/<rect[\s\S]*?tabIndex/.test(chartSource) && !/<circle[\s\S]*?tabIndex/.test(chartSource), '柱和点不得进入 Tab 顺序')
assert(chartSource.includes('xAxisTicks'), '图表必须绘制日期刻度')
assert(!pageSource.includes('recharts') && !pageSource.includes('echarts'), '不得新增图表依赖')

console.log('warehouseProductFlow.sourceContract.test: ok')
