import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

// CI 的 web-esbuild lane 从 apps/web 执行测试。
const page = readFileSync('src/pages/ExecutiveSalesIntelligence/index.tsx', 'utf8')
const hierarchy = readFileSync('src/pages/ExecutiveSalesIntelligence/RevenueReport/RevenueWeeklyHierarchy.tsx', 'utf8')
const logic = readFileSync('src/pages/ExecutiveSalesIntelligence/RevenueReport/logic.ts', 'utf8')
const styles = readFileSync('src/pages/ExecutiveSalesIntelligence/styles.module.css', 'utf8')

assert.match(page, /useKeepAliveContext\(\)/, 'keepAlive 页面必须读取 active 状态')
assert.match(page, /useLocation\(\)/, '营业额返回参数必须从 URL 恢复')
assert.match(page, /buildRevenueOverviewSearch/, '日期和分店筛选必须同步回 URL 以支持刷新')
assert.match(page, /useReportQuery<RevenueBranch\[\]>/, '分店排名必须使用独立可取消查询')
assert.match(page, /useReportQuery<RevenueHourly\[\]>/, '时段必须使用独立可取消查询')
assert.match(page, /useReportQuery<RevenueWeeklyNode\[\]>/, '周层级必须使用独立可取消查询')
assert.match(page, /makeRevenueQueryScope\(currentUser\?\.userGUID, managedStoreCodes\)/, '缓存键必须含用户与授权分店范围')
assert.match(page, /Boolean\(currentUser\).*managedStoreCodes\.length > 0/, '无用户或无授权分店时不得发送查询')
assert.match(page, /weeklyNearViewport[\s\S]*branchQuery\.error/, '周层级必须在接近视口或核心查询结束后再启用')
assert.match(page, /fetchRevenueWeekly\(period, hourlyBranchCodes, signal\)/, '选中门店后周层级也必须使用同一门店范围')
assert.match(page, /IntersectionObserver/, '周层级应支持视口渐进加载')
assert.match(page, /<ReportControls/, '营业额与销售明细必须复用统一日期控件')
assert.match(page, /onChange=\{nextSelection => commitFilters\(nextSelection, selectedBranch\)\}/, '日期与同比变化必须同步 URL')
assert.match(page, /commitFilters\(selection, null\)/, '清除分店必须同步移除 URL 分店参数')
assert.match(page, /buildSalesDetailPath/, '分店必须可反查销售明细并携带筛选条件')
assert.match(logic, /compare:\s*String\(selection\.compare\)[\s\S]*compareMode:\s*selection\.compareMode/, '销售明细反查必须保留同比开关和口径')
assert.doesNotMatch(page, /location\.search === expected \|\| !location\.search/, '返回无查询参数 URL 时必须清除保活筛选状态')
assert.match(page, /<ValuePair current=\{formatAud\(branch\.revenue\)\}/, '门店本期与同期金额必须共用紧凑双行单元格')
assert.doesNotMatch(page, /首批数据|First data/, '接口完成时长不得误称为首批绘制时长')
assert.match(page, /aria-live="polite"/, '筛选上下文与加载状态必须可被读屏器感知')
assert.match(page, /aria-pressed=\{selected\}/, '分店选择必须暴露按下状态')
assert.match(hierarchy, /aria-expanded=\{expanded\}/, '周与分店层级必须暴露展开状态')
assert.match(hierarchy, /onSelectDate/, '日期节点必须支持回写主日期筛选')
assert.match(hierarchy, /getHierarchyDateRange\(node, queryRange\)/, '周点击范围必须按 ISO 周边界与查询范围裁剪')
assert.match(hierarchy, /MetricPair current=\{node\.revenue\}[\s\S]*MetricPair current=\{node\.orders\}[\s\S]*MetricPair current=\{node\.aov\}/, '周层级必须保留销售额、订单和客单价的本期同期字段')
assert.match(hierarchy, /renderTrend\(node\.revenue[\s\S]*renderTrend\(node\.orders[\s\S]*renderTrend\(node\.aov/, '周层级三个指标都必须保留同比')
assert.match(page, /commitFilters\(nextSelection, nextBranch\)/, '层级日期与分店必须一次性写入同一 URL 状态')
assert.match(page, /setBranchRefresh[\s\S]*setHourlyRefresh[\s\S]*setWeeklyRefresh/, '顶栏刷新必须刷新全部区域')
assert.match(page, /SectionError message=\{branchQuery\.error\}[\s\S]*setBranchRefresh/, '分店区域重试不得放大为全页请求')
assert.match(page, /selectedBranch[\s\S]*订单同比/, '单店决策信号不得继续显示全店数量')
assert.match(hierarchy, /onKeyDown/, '可选择的层级行必须支持键盘操作')
assert.match(styles, /overflow-x:\s*auto/, '高密度数据表必须内部横向滚动')
assert.match(styles, /:focus-visible/, '所有自定义交互必须有可见键盘焦点')
assert.match(styles, /prefers-reduced-motion/, '状态动效必须尊重减少动态偏好')
assert.match(styles, /font-variant-numeric:\s*tabular-nums/, '金额与数量必须使用等宽数字')

console.log('营业额页面请求、联动、可访问性与样式契约：通过')
