import type { CurrentUser, UserStoreDto } from "../auth/types";

export const IOS_REVIEW_PERMISSION_CODES = [
  "Orders.View",
  "Orders.Create",
  "Orders.Edit",
  "Orders.Delete",
  "Products.View",
  "Products.Create",
  "Products.Edit",
  "Products.Delete",
  "PosProducts.Manage",
  "StoreProducts.View",
  "StoreProducts.Create",
  "StoreProducts.Edit",
  "Prices.Modify",
  "Prices.Delete",
  "Users.View",
  "Users.Create",
  "Users.Edit",
  "Users.Delete",
  "Users.ManagePosTerminalPermissions",
  "Roles.View",
  "Roles.Create",
  "Roles.Edit",
  "Roles.Delete",
  "Stores.View",
  "Stores.Create",
  "Stores.Edit",
  "Stores.Delete",
  "Warehouse.Manage",
  "Warehouse.ManageProducts",
  "Container.View",
  "Container.Create",
  "Container.Edit",
  "Container.Delete",
  "DomesticPurchase.ManageProducts",
  "LocalPurchase.View",
  "LocalPurchase.Edit",
  "LocalPurchase.PushToHq",
  "InstallmentOrders.View",
  "Advertisements.View",
  "Advertisements.Edit",
  "Promotions.View",
  "StoreVouchers.View",
  "SeasonalCards.Remaining.ViewManagedStore",
  "SeasonalCards.Remaining.SubmitManagedStore",
  "Attendance.Schedule.ViewSelf",
  "Attendance.Schedule.ViewStore",
  "Attendance.Schedule.EditManagedStore",
  "Attendance.Availability.SubmitSelf",
  "Attendance.Availability.ViewManagedStore",
  "Attendance.Punch.Self",
  "Attendance.Punch.ViewManagedStore",
  "Attendance.Approval.ViewManagedStore",
  "Attendance.Approval.ReviewManagedStore",
  "Attendance.Holiday.ViewStore",
  "Attendance.Holiday.EditManagedStore",
  "Attendance.Leave.ApplySelf",
  "Attendance.Leave.ViewManagedStore",
  "Attendance.Leave.ReviewManagedStore",
  "Attendance.Settings.Edit",
  "Attendance.Admin.View",
  "EmployeeProfiles.View",
  "DeviceRegistration.View",
  "DeviceRegistration.Manage",
  "Reports.View",
  "Reports.ProductMovement.View",
  "Reports.Export",
  "PosTerminal.Sales.AddItem",
  "PosTerminal.Sales.RemoveLine",
  "PosTerminal.Payment.TakeCash",
] as const;

export const IOS_REVIEW_STORES: ReadonlyArray<UserStoreDto> = [
  {
    storeGUID: "8f42dc5b-77ce-46ea-94a4-6f73ddcce001",
    storeCode: "REV001",
    storeName: "Demo Brisbane",
    postcode: "4000",
    stateCode: "QLD",
    isPrimary: true,
    assignedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    storeGUID: "8f42dc5b-77ce-46ea-94a4-6f73ddcce002",
    storeCode: "REV002",
    storeName: "Demo Gold Coast",
    postcode: "4217",
    stateCode: "QLD",
    assignedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    storeGUID: "8f42dc5b-77ce-46ea-94a4-6f73ddcce003",
    storeCode: "REVWH",
    storeName: "Demo Warehouse",
    postcode: "4108",
    stateCode: "QLD",
    assignedAt: "2026-01-01T00:00:00.000Z",
  },
];

export function createIosReviewUser(): CurrentUser {
  const stores = IOS_REVIEW_STORES.map((store) => ({ ...store }));
  return {
    userGuid: "92c2cc51-4123-4ea1-a25c-2eed0caf0001",
    userGUID: "92c2cc51-4123-4ea1-a25c-2eed0caf0001",
    username: "ios_app_review",
    email: "ios-app-review@example.invalid",
    fullName: "App Review Demo",
    phone: "+61 400 000 001",
    permissions: [...IOS_REVIEW_PERMISSION_CODES],
    roleNames: ["Admin"],
    storeNames: stores.map((store) => store.storeName),
    stores,
  };
}
