const paymentRecoveryEnglishCopy = {
  "title": "Payment recovery centre",
  "subtitle": "Resolve interrupted card payments without blocking the next sale.",
  "action.back": "Back to sale · Start next sale",
  "action.backShort": "Back to sale",
  "action.refresh": "Refresh",
  "action.refreshing": "Refreshing…",
  "action.recover": "Check and recover original payment",
  "action.recovering": "Checking original payment…",
  "action.resume": "Continue payment for original order",
  "action.manual": "Manually verify payment",
  "action.close": "Cancel",
  "action.submit.paid": "Verify supervisor and confirm payment",
  "action.submit.unpaid": "Verify supervisor and confirm no payment",
  "action.submit.uncertain": "Verify supervisor and keep awaiting recovery",
  "action.submitting": "Saving verification…",
  "filter.pending": "Awaiting recovery",
  "filter.failed": "Failed",
  "filter.resolved": "Resolved",
  "search.label": "Search recovery records",
  "search.placeholder": "Order or transaction reference",
  "list.title": "Payment records",
  "list.empty": "No payment records match this view.",
  "list.loading": "Loading payment recovery records…",
  "state.unavailable": "Payment recovery is unavailable. Saved exceptions are retained.",
  "details.select": "Select a payment record to review its evidence and actions.",
  "details.amount": "Amount",
  "details.order": "Order",
  "details.transaction": "Original transaction reference",
  "details.receipt": "Receipt reference",
  "details.terminal": "Terminal",
  "details.unavailable": "Unavailable",
  "details.items": "Items",
  "details.quantity": "Qty {{quantity}}",
  "details.history": "Handling history",
  "details.noHistory": "No handling history recorded.",
  "details.evidence": "Evidence: {{value}}",
  "details.note": "Note: {{value}}",
  "details.supervisor": "Supervisor: {{value}}",
  "details.source.provider": "Payment provider",
  "details.source.operator": "Operator",
  "details.source.system": "System",
  "event.attempt-created": "Card payment attempt saved",
  "event.provider-query-started": "Original provider payment queried",
  "event.provider-paid": "Payment provider confirmed payment",
  "event.provider-failed": "Payment provider confirmed failure",
  "event.operator-paid": "Operator recorded payment as received",
  "event.operator-unpaid": "Operator recorded that no payment was taken",
  "event.operator-uncertain": "Operator kept the result awaiting recovery",
  "event.provider-manual-conflict": "Provider result conflicts with the manual finding",
  "event.order-completed": "Original order completed",
  "status.result-unknown": "Result unknown",
  "status.payment-failed": "Payment failed",
  "status.charged-order-incomplete": "Paid · Order incomplete",
  "status.manual-paid": "Manually confirmed paid",
  "status.manual-unpaid": "Manually confirmed unpaid",
  "status.provider-recovered": "Recovered from provider",
  "status.review-required": "Review required",
  "statusHint.result-unknown": "Do not charge again. Check the original provider attempt first.",
  "statusHint.payment-failed": "The provider reported a definite failure. Review the record before retrying.",
  "statusHint.charged-order-incomplete": "Payment evidence exists. Complete this order without charging again.",
  "statusHint.manual-paid": "An operator confirmed payment evidence. This is not a provider approval.",
  "statusHint.manual-unpaid": "An operator confirmed that no payment was taken.",
  "statusHint.provider-recovered": "The original payment was confirmed by the payment provider.",
  "statusHint.review-required": "Provider evidence and the manual finding conflict. A supervisor must review it.",
  "manual.title": "Manually verify payment",
  "manual.subtitle": "Record what was checked. Manual verification is kept separate from provider approval.",
  "manual.order": "Order {{order}} · Expected {{amount}}",
  "manual.finding": "Verification result",
  "manual.finding.paid": "Paid",
  "manual.finding.paidHint": "Payment was taken. Complete this order without charging again.",
  "manual.finding.unpaid": "Confirmed unpaid",
  "manual.finding.unpaidHint": "No payment was taken. The original order may be paid again.",
  "manual.finding.uncertain": "Still uncertain",
  "manual.finding.uncertainHint": "Keep the record awaiting recovery and do not charge it again.",
  "manual.amount": "Verified amount",
  "manual.amountPlaceholder": "0.00",
  "manual.evidence": "Receipt or transaction reference",
  "manual.evidencePlaceholder": "Enter the terminal receipt or reference",
  "manual.note": "Verification note",
  "manual.notePlaceholder": "Describe where and how the payment was checked",
  "manual.authorization": "Supervisor verification",
  "manual.authorizationConfirm": "I confirm these details are accurate and ready for supervisor verification.",
  "manual.authorizationHint": "Submitting opens the supervisor identity check. The result is saved only after authorization succeeds.",
  "manual.auditNotice": "The operator, time, evidence and finding will be recorded for audit.",
  "validation.finding": "Select a verification result.",
  "validation.amount": "Enter a valid verified amount.",
  "validation.amountMismatch": "The verified amount must match {{amount}}.",
  "validation.evidence": "Enter a receipt or transaction reference.",
  "validation.note": "Enter a verification note.",
  "validation.authorization": "Confirm the details before requesting supervisor authorization.",
  "error.RECOVERY_CURRENT_SALE_BUSY": "Finish or hold the current sale before reopening an earlier order.",
  "error.RECOVERY_PROVIDER_UNAVAILABLE": "The payment provider is unavailable. Keep this record and reconnect before checking again.",
  "error.RECOVERY_TERMINAL_CONFIRMATION_PENDING": "Payment is recorded, but the terminal confirmation is still pending. Check the original payment again; do not charge again.",
  "error.RECOVERY_AUTHORIZATION_DENIED": "Supervisor authorization was not completed. No manual finding was saved.",
  "error.RECOVERY_SESSION_CHANGED": "The cashier session changed. Sign in again before continuing.",
  "error.load": "Payment recovery records could not be loaded.",
  "error.RECOVERY_LOAD_FAILED": "Payment recovery records could not be loaded.",
  "error.RECOVERY_ACTION_FAILED": "The processing result cannot be confirmed yet. Refresh the original record and do not charge again.",
  "error.RECOVERY_BUSY": "Another recovery action is in progress. Wait for it to finish.",
  "error.action": "The processing result cannot be confirmed yet. Refresh the original record and do not charge again.",
} as const;

export type PaymentRecoveryCopyKey = keyof typeof paymentRecoveryEnglishCopy;

const paymentRecoveryChineseCopy = {
  "title": "支付恢复中心",
  "subtitle": "集中处理刷卡中断和异常，不影响下一笔收银。",
  "action.back": "返回收银 · 开始下一单",
  "action.backShort": "返回收银",
  "action.refresh": "刷新",
  "action.refreshing": "刷新中…",
  "action.recover": "查询并恢复原支付",
  "action.recovering": "正在查询原支付…",
  "action.resume": "继续原订单付款",
  "action.manual": "人工核实付款",
  "action.close": "取消",
  "action.submit.paid": "验证主管并确认已收款",
  "action.submit.unpaid": "验证主管并确认未收款",
  "action.submit.uncertain": "验证主管并继续等待恢复",
  "action.submitting": "正在保存核实结果…",
  "filter.pending": "待恢复",
  "filter.failed": "已失败",
  "filter.resolved": "已处理",
  "search.label": "搜索恢复记录",
  "search.placeholder": "订单号或交易号",
  "list.title": "支付记录",
  "list.empty": "当前分类没有符合条件的支付记录。",
  "list.loading": "正在读取支付恢复记录…",
  "state.unavailable": "支付恢复服务暂不可用，已保存的异常交易不会被删除。",
  "details.select": "请选择支付记录，查看凭证和可执行操作。",
  "details.amount": "待核实金额",
  "details.order": "订单号",
  "details.transaction": "原交易号",
  "details.receipt": "小票参考号",
  "details.terminal": "刷卡终端",
  "details.unavailable": "暂无",
  "details.items": "商品明细",
  "details.quantity": "数量 {{quantity}}",
  "details.history": "处理记录",
  "details.noHistory": "暂无处理记录。",
  "details.evidence": "核实凭证：{{value}}",
  "details.note": "核实备注：{{value}}",
  "details.supervisor": "授权主管：{{value}}",
  "details.source.provider": "支付方",
  "details.source.operator": "操作人",
  "details.source.system": "系统",
  "event.attempt-created": "已保存刷卡支付尝试",
  "event.provider-query-started": "已查询原支付方交易",
  "event.provider-paid": "支付方确认已付款",
  "event.provider-failed": "支付方确认支付失败",
  "event.operator-paid": "操作人记录为已收款",
  "event.operator-unpaid": "操作人记录为未扣款",
  "event.operator-uncertain": "操作人保留为待恢复",
  "event.provider-manual-conflict": "支付方结果与人工结论冲突",
  "event.order-completed": "已完成原订单",
  "status.result-unknown": "支付结果未知",
  "status.payment-failed": "支付失败",
  "status.charged-order-incomplete": "已扣款 · 订单未完成",
  "status.manual-paid": "人工确认已收款",
  "status.manual-unpaid": "人工确认未收款",
  "status.provider-recovered": "支付方已恢复",
  "status.review-required": "待复核",
  "statusHint.result-unknown": "禁止再次扣款，请先查询原支付尝试。",
  "statusHint.payment-failed": "支付方已明确返回失败，请核对记录后再处理。",
  "statusHint.charged-order-incomplete": "已有付款凭证，请补齐原订单，禁止再次扣款。",
  "statusHint.manual-paid": "操作人已核实付款凭证；该结果不代表支付方批准。",
  "statusHint.manual-unpaid": "操作人已核实本次没有扣款。",
  "statusHint.provider-recovered": "原支付已由支付方确认。",
  "statusHint.review-required": "支付方结果与人工结论冲突，需要主管复核。",
  "manual.title": "人工核实付款",
  "manual.subtitle": "记录实际核实依据。人工结论与支付方批准分别保存。",
  "manual.order": "订单 {{order}} · 应付 {{amount}}",
  "manual.finding": "核实结果",
  "manual.finding.paid": "已扣款",
  "manual.finding.paidHint": "确认款项已扣，补齐原订单，不再次扣款。",
  "manual.finding.unpaid": "确认未扣款",
  "manual.finding.unpaidHint": "确认本次未扣款，可让原订单重新选择付款。",
  "manual.finding.uncertain": "仍无法确认",
  "manual.finding.uncertainHint": "继续留在待恢复，原订单禁止再次扣款。",
  "manual.amount": "核实金额",
  "manual.amountPlaceholder": "0.00",
  "manual.evidence": "终端小票号或交易参考号",
  "manual.evidencePlaceholder": "请输入小票号或交易参考号",
  "manual.note": "核实备注",
  "manual.notePlaceholder": "请说明在哪里、通过什么方式核实",
  "manual.authorization": "主管身份验证",
  "manual.authorizationConfirm": "我确认以上信息准确，可以提交主管验证。",
  "manual.authorizationHint": "提交后将打开主管身份验证，只有授权成功才会保存处理结果。",
  "manual.auditNotice": "系统将记录操作人、时间、凭证和核实结论，供审计查询。",
  "validation.finding": "请选择核实结果。",
  "validation.amount": "请输入有效的核实金额。",
  "validation.amountMismatch": "核实金额必须与 {{amount}} 一致。",
  "validation.evidence": "请输入终端小票号或交易参考号。",
  "validation.note": "请输入核实备注。",
  "validation.authorization": "申请主管授权前，请确认以上信息准确。",
  "error.RECOVERY_CURRENT_SALE_BUSY": "请先完成或挂起当前交易，再打开之前的订单。",
  "error.RECOVERY_PROVIDER_UNAVAILABLE": "支付服务暂不可用，请保留记录，恢复连接后再查询。",
  "error.RECOVERY_TERMINAL_CONFIRMATION_PENDING": "款项已入账，终端确认尚未完成。请再次查询原支付，勿重复扣款。",
  "error.RECOVERY_AUTHORIZATION_DENIED": "主管授权未完成，未保存人工核实结论。",
  "error.RECOVERY_SESSION_CHANGED": "收银员会话已变化，请重新登录后继续。",
  "error.load": "无法读取支付恢复记录。",
  "error.RECOVERY_LOAD_FAILED": "无法读取支付恢复记录。",
  "error.RECOVERY_ACTION_FAILED": "暂时无法确认处理结果，请刷新核对原记录，勿重复扣款。",
  "error.RECOVERY_BUSY": "另一项恢复操作正在进行，请等待完成。",
  "error.action": "暂时无法确认处理结果，请刷新核对原记录，勿重复扣款。",
} as const satisfies Record<PaymentRecoveryCopyKey, string>;

const copy = { en: paymentRecoveryEnglishCopy, zh: paymentRecoveryChineseCopy } as const;

export type PaymentRecoveryLocale = keyof typeof copy;

export function resolvePaymentRecoveryLocale(language?: string): PaymentRecoveryLocale {
  return language?.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function paymentRecoveryText(
  locale: PaymentRecoveryLocale,
  key: PaymentRecoveryCopyKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  const template = copy[locale][key];
  if (!values) return template;
  return template.replace(/\{\{(\w+)\}\}/gu, (placeholder, name: string) => {
    const value = values[name];
    return value === undefined ? placeholder : String(value);
  });
}
