export const returnEnglishCopy = {
  title: "Returns",
  subtitle: "Refund only against verified line and original tender capacity.",
  "mode.receipt": "Receipt return",
  "mode.noReceipt": "No receipt",
  "action.back": "Back",
  "action.backToSelection": "Back to items",
  "action.requery": "Change order",
  "action.next": "Next",
  "action.search": "Find order",
  "action.addProduct": "Add product",
  "action.addOpenItem": "Add OPENITEM",
  "action.decrease": "Decrease quantity",
  "action.increase": "Increase quantity",
  "action.confirm": "Confirm refund",
  "action.recover": "Recover refund",
  "action.reset": "Start another return",
  "search.orderLabel": "Receipt or order number",
  "search.orderPlaceholder": "Scan or enter an order number",
  "search.productLabel": "No-receipt product",
  "search.productPlaceholder": "Scan or enter a product barcode",
  "openItem.nameLabel": "OPENITEM description",
  "openItem.namePlaceholder": "Describe the returned item",
  "openItem.amountLabel": "Unit refund amount",
  "openItem.amountPlaceholder": "0.00",
  "order.summary": "Order {{order}}",
  "order.remote": "Verified online",
  "order.local": "Verified local copy",
  "order.stale": "Return records may be stale. Only proven local cash capacity is available offline.",
  "lines.title": "Items to return",
  "lines.empty": "Find an order or add a supervised no-receipt item.",
  "lines.noneReturnable": "This order has no returnable items.",
  "line.itemNumber": "Item {{itemNumber}}",
  "line.quantity": "{{selected}} of {{available}}",
  "line.quantityNoReceipt": "Quantity {{selected}}",
  "line.refund": "Refund {{amount}}",
  "capacity.title": "Original tender capacity",
  "capacity.noReceipt": "No original tender capacity. This supervised return must stay online.",
  "capacity.remaining": "{{method}} · {{amount}} available",
  "method.cash": "Cash",
  "method.card": "Card",
  "method.voucher": "Voucher",
  "method.installment": "Installment",
  "summary.title": "Refund plan",
  "summary.selected": "Selected refund",
  "summary.total": "Refund total",
  "summary.method": "Preferred tender",
  "summary.rule": "The final plan may split across original tenders. Card, voucher and installment refunds require online recovery.",
  "summary.ruleReceiptDefault": "Refunds default to the original tender. Cash or voucher may be selected instead.",
  "status.waitingTitle": "Refund in progress",
  "status.waitingHint": "Keep this screen open. Do not retry or change tender.",
  "status.unknownTitle": "Refund outcome unknown",
  "status.unknownHint": "Do not refund again. Reconnect and recover the existing payment attempt.",
  "status.successTitle": "Refund completed",
  "status.successOrder": "Return order {{order}}",
  "status.successAmount": "{{amount}} refunded",
  "status.failedTitle": "Refund not completed",
  "status.failedHint": "No automatic retry was made. Follow the stable error below.",
  "error.RETURN_QUERY_REQUIRED": "Enter an order or product number.",
  "error.RETURN_ORDER_NOT_FOUND": "The order was not found.",
  "error.RETURN_PRODUCT_NOT_FOUND": "The product was not found.",
  "error.RETURN_SOURCE_MISMATCH": "The return source does not match the verified order.",
  "error.RETURN_LINE_NOT_FOUND": "That return line is no longer available.",
  "error.RETURN_QUANTITY_INVALID": "Return quantity must be a whole number.",
  "error.RETURN_QUANTITY_EXCEEDED": "Return quantity exceeds the verified remaining quantity.",
  "error.RETURN_AMOUNT_EXCEEDED": "Refund amount exceeds the verified remaining amount.",
  "error.RETURN_NO_LINES_SELECTED": "Select at least one item to return.",
  "error.RETURN_CAPACITY_EXCEEDED": "Refund exceeds the remaining original tender capacity.",
  "error.RETURN_ONLINE_REQUIRED": "This refund requires an online connection.",
  "error.RETURN_SUPERVISOR_REQUIRED": "Supervisor authorization is required.",
  "error.RETURN_OPEN_ITEM_INVALID": "Enter a valid OPENITEM description and amount.",
  "error.RETURN_UNKNOWN_RECOVERY_REQUIRED": "Recover the existing unknown refund before any other action.",
  "error.RETURN_OPERATION_IN_PROGRESS": "A refund action is already in progress.",
  "error.RETURN_SESSION_EXPIRED": "The cashier session changed. Sign in again before continuing.",
  "error.RETURN_LOOKUP_FAILED": "The return lookup could not be completed.",
  "error.RETURN_EXECUTION_DECLINED": "The refund was declined.",
  "error.RETURN_EXECUTION_FAILED": "The refund could not be completed and was not automatically retried.",
  "error.RETURN_RECOVERY_FAILED": "Recovery did not complete. Keep this refund in recovery.",
} as const;

export type ReturnCopyKey = keyof typeof returnEnglishCopy;

const returnChineseCopy = {
  title: "退货",
  subtitle: "仅按已核验的原明细与原支付容量退款。",
  "mode.receipt": "小票退货",
  "mode.noReceipt": "无小票退货",
  "action.back": "返回",
  "action.backToSelection": "返回选品",
  "action.requery": "重新查询",
  "action.next": "下一步",
  "action.search": "查询原单",
  "action.addProduct": "添加商品",
  "action.addOpenItem": "添加 OPENITEM",
  "action.decrease": "减少数量",
  "action.increase": "增加数量",
  "action.confirm": "确认退款",
  "action.recover": "恢复退款",
  "action.reset": "开始下一笔退货",
  "search.orderLabel": "小票号或订单号",
  "search.orderPlaceholder": "扫描或输入订单号",
  "search.productLabel": "无小票商品",
  "search.productPlaceholder": "扫描或输入商品条码",
  "openItem.nameLabel": "OPENITEM 说明",
  "openItem.namePlaceholder": "说明退回商品",
  "openItem.amountLabel": "单件退款金额",
  "openItem.amountPlaceholder": "0.00",
  "order.summary": "原单 {{order}}",
  "order.remote": "已在线核验",
  "order.local": "已核验本地副本",
  "order.stale": "退货记录可能不是最新；离线时仅可使用可证明的本地现金容量。",
  "lines.title": "选择退货商品",
  "lines.empty": "请查询原单，或添加经主管授权的无小票商品。",
  "lines.noneReturnable": "该原单没有可退商品。",
  "line.itemNumber": "货号 {{itemNumber}}",
  "line.quantity": "已选 {{selected}} / 可退 {{available}}",
  "line.quantityNoReceipt": "数量 {{selected}}",
  "line.refund": "退款 {{amount}}",
  "capacity.title": "原支付退款容量",
  "capacity.noReceipt": "无原支付容量；此主管授权退货必须保持在线。",
  "capacity.remaining": "{{method}} · 可退 {{amount}}",
  "method.cash": "现金",
  "method.card": "银行卡",
  "method.voucher": "礼券",
  "method.installment": "分期",
  "summary.title": "退款计划",
  "summary.selected": "已选退款",
  "summary.total": "退款合计",
  "summary.method": "优先退款方式",
  "summary.rule": "最终计划可按原支付容量拆分；银行卡、礼券和分期退款必须在线恢复。",
  "summary.ruleReceiptDefault": "默认按原支付方式退回；也可选择现金或代金券代替。",
  "status.waitingTitle": "正在退款",
  "status.waitingHint": "请保持此页面，不要重试或更换退款方式。",
  "status.unknownTitle": "退款结果未知",
  "status.unknownHint": "禁止再次退款；联网后恢复已有支付尝试。",
  "status.successTitle": "退款完成",
  "status.successOrder": "退货单 {{order}}",
  "status.successAmount": "已退款 {{amount}}",
  "status.failedTitle": "退款未完成",
  "status.failedHint": "系统未自动重试，请按下方稳定错误处理。",
  "error.RETURN_QUERY_REQUIRED": "请输入订单号或商品号。",
  "error.RETURN_ORDER_NOT_FOUND": "未找到原订单。",
  "error.RETURN_PRODUCT_NOT_FOUND": "未找到商品。",
  "error.RETURN_SOURCE_MISMATCH": "退货来源与已核验原单不一致。",
  "error.RETURN_LINE_NOT_FOUND": "该退货明细已不可用。",
  "error.RETURN_QUANTITY_INVALID": "退货数量必须为整数。",
  "error.RETURN_QUANTITY_EXCEEDED": "退货数量超过已核验可退数量。",
  "error.RETURN_AMOUNT_EXCEEDED": "退款金额超过已核验剩余金额。",
  "error.RETURN_NO_LINES_SELECTED": "请至少选择一件退货商品。",
  "error.RETURN_CAPACITY_EXCEEDED": "退款超过原支付剩余容量。",
  "error.RETURN_ONLINE_REQUIRED": "此退款必须联网处理。",
  "error.RETURN_SUPERVISOR_REQUIRED": "需要主管授权。",
  "error.RETURN_OPEN_ITEM_INVALID": "请输入有效的 OPENITEM 说明和金额。",
  "error.RETURN_UNKNOWN_RECOVERY_REQUIRED": "完成当前未知退款恢复前禁止其他操作。",
  "error.RETURN_OPERATION_IN_PROGRESS": "已有退款操作正在进行。",
  "error.RETURN_SESSION_EXPIRED": "收银员会话已变化，请重新登录后继续。",
  "error.RETURN_LOOKUP_FAILED": "无法完成退货查询。",
  "error.RETURN_EXECUTION_DECLINED": "退款已被拒绝。",
  "error.RETURN_EXECUTION_FAILED": "退款未完成，系统没有自动重试。",
  "error.RETURN_RECOVERY_FAILED": "恢复尚未完成，请保持此退款为恢复状态。",
} as const satisfies Record<ReturnCopyKey, string>;

const returnCopy = {
  en: returnEnglishCopy,
  zh: returnChineseCopy,
} as const;

export type ReturnLocale = keyof typeof returnCopy;

export function resolveReturnLocale(language?: string): ReturnLocale {
  return language?.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function returnText(
  locale: ReturnLocale,
  key: ReturnCopyKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  const template = returnCopy[locale][key];
  if (!values) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name: string) => {
    const value = values[name];
    return value === undefined ? placeholder : String(value);
  });
}
