export const installmentEnglishCopy = {
  eyebrow: "STORE OPERATIONS",
  title: "Installments",
  subtitle:
    "History may use the local cache; all mutations require a live backend.",
  offline: "Offline: cached viewing only; every installment write is locked.",
  "action.recover": "Recover previous action",
  "action.back": "Back",
  "action.history": "History",
  "action.new": "New",
  "action.search": "Search",
  "action.addRepayment": "Add repayment",
  "action.refundCancel": "Refund & cancel",
  "action.void": "Void",
  "action.confirmPickup": "Confirm pickup",
  "action.confirm": "Confirm",
  "action.create": "Create & take down payment",
  "action.backToSales": "Back to sales",
  "action.working": "Working…",
  "filter.all": "All",
  "filter.active": "Active",
  "filter.paid": "Paid",
  "filter.picked": "Picked",
  "filter.cancelled": "Cancelled",
  "history.title": "Installment history",
  "history.count": "{{count}} items",
  "search.accessibility": "Search installments",
  "search.placeholder": "Number, customer, phone",
  "history.loading": "Loading…",
  "history.empty": "No installment records",
  "balance.label": "Balance",
  "details.loading": "Loading details…",
  "details.empty": "Select an installment",
  "details.offlineHint":
    "When no encrypted detail cache is available offline, this screen will not start a network write.",
  "metric.total": "Total",
  "metric.down": "Down payment",
  "metric.paid": "Paid",
  "metric.balance": "Balance",
  "section.items": "Items",
  "section.payments": "Payment history",
  "section.note": "Note",
  "payments.empty": "No recorded payments",
  "completed.picked": "Picked up",
  "completed.cancelled": "Cancelled",
  "repayment.title": "Add repayment",
  "repayment.amountAccessibility": "Repayment amount",
  "repayment.voucherAccessibility": "Repayment voucher code",
  "voucher.placeholder": "Voucher code",
  "voucher.help":
    "Enter the voucher code only; the online payment provider will query and lock it after submission.",
  "cancel.title": "Cancel installment",
  "cancel.reasonAccessibility": "Cancellation reason",
  "cancel.reasonPlaceholder": "Refund-cancel reason",
  "void.reasonAccessibility": "Void reason",
  "void.reasonPlaceholder": "Void reason",
  "pickup.title": "Confirm pickup",
  "pickup.noteAccessibility": "Pickup note",
  "pickup.notePlaceholder": "ID check or note",
  "confirmation.cancel":
    "The original payments will be refunded, then the installment will be cancelled after the result is known.",
  "confirmation.void":
    "Voiding does not refund; use it only for an incorrect installment that needs no refund.",
  "confirmation.pickup":
    "The installment will be marked as picked up after confirmation.",
  "cart.title": "Current cart",
  "cart.hint":
    "The composition root checks the cart revision again when creating. This screen snapshot cannot replace the live cart.",
  "cart.empty": "Current cart is empty",
  "create.title": "Customer & down payment",
  "create.customerNameAccessibility": "Customer name",
  "create.customerNamePlaceholder": "Customer name",
  "create.customerPhoneAccessibility": "Customer phone",
  "create.customerPhonePlaceholder": "Customer phone",
  "create.noteAccessibility": "Installment note",
  "create.notePlaceholder": "Note",
  "create.downPayment": "Down payment",
  "create.downPaymentAccessibility": "Down payment amount",
  "create.voucherAccessibility": "Down payment voucher code",
  "create.minimums":
    "Minimum installment total {{total}}; minimum down payment {{downPayment}}.",
  "draft.count": "{{count}} items",
  "method.cash": "Cash",
  "method.card": "Card",
  "method.voucher": "Voucher",
  "status.Active": "Active",
  "status.PaidOff": "Paid off",
  "status.PickedUp": "Picked up",
  "status.Cancelled": "Cancelled",
  "paymentStatus.Recorded": "Recorded",
  "paymentStatus.Voided": "Voided",
  "cancellation.RefundCancel": "Refunded and cancelled",
  "cancellation.VoidCancel": "Voided",
  "unavailable.title": "Installments unavailable",
  "unavailable.subtitle":
    "The trusted payment and cache runtime is not configured.",
  "status.action-failed": "Operation failed. Check the state and try again.",
  "status.authorization-declined":
    "Payment was declined; no installment change was made.",
  "status.cancel-complete": "Installment refunded and cancelled.",
  "status.conflict": "Server state changed; refresh first.",
  "status.create-complete": "Installment and down payment recorded.",
  "status.details-failed": "Unable to load details.",
  "status.details-unavailable": "No cached details are available.",
  "status.history-failed": "Unable to load history.",
  "status.invalid-create":
    "Check the cart, customer, minimum AUD 50 total and minimum AUD 20 down payment.",
  "status.invalid-repayment": "Repayment amount or tender is invalid.",
  "status.online-required": "This operation requires a live backend.",
  "status.payment-recovery-required":
    "Payment outcome unknown; recovery is required before any new action.",
  "status.permission-required": "Cashier permission is required.",
  "status.pickup-complete": "Pickup confirmed.",
  "status.repayment-complete": "Repayment recorded.",
  "status.recovery-complete":
    "Previous payment and installment action recovered.",
  "status.void-complete": "Installment voided.",
} as const;

export type InstallmentCopyKey = keyof typeof installmentEnglishCopy;

const installmentChineseCopy = {
  eyebrow: "门店运营",
  title: "分期",
  subtitle: "历史可从本机缓存读取；所有创建、付款、退款和状态变更必须在线。",
  offline:
    "离线模式：仅可浏览本机加密缓存；创建、首付、补款、取消、作废和取货均已锁定。",
  "action.recover": "恢复上一笔",
  "action.back": "返回",
  "action.history": "历史",
  "action.new": "新建",
  "action.search": "查询",
  "action.addRepayment": "记录续付",
  "action.refundCancel": "退款并取消",
  "action.void": "作废",
  "action.confirmPickup": "确认已取货",
  "action.confirm": "确认",
  "action.create": "创建分期并收取首付",
  "action.backToSales": "返回销售",
  "action.working": "处理中…",
  "filter.all": "全部",
  "filter.active": "进行中",
  "filter.paid": "已付清",
  "filter.picked": "已取货",
  "filter.cancelled": "已取消",
  "history.title": "分期历史",
  "history.count": "{{count}} 项",
  "search.accessibility": "搜索分期",
  "search.placeholder": "分期号、客户、电话",
  "history.loading": "正在读取…",
  "history.empty": "暂无分期记录",
  "balance.label": "余额",
  "details.loading": "正在读取详情…",
  "details.empty": "选择一张分期单",
  "details.offlineHint":
    "离线时若本机没有加密详情缓存，页面不会向网络发起写操作。",
  "metric.total": "总额",
  "metric.down": "首付",
  "metric.paid": "已付",
  "metric.balance": "余额",
  "section.items": "商品",
  "section.payments": "付款历史",
  "section.note": "备注",
  "payments.empty": "暂无付款",
  "completed.picked": "已取货",
  "completed.cancelled": "已取消",
  "repayment.title": "续付",
  "repayment.amountAccessibility": "续付金额",
  "repayment.voucherAccessibility": "续付券码",
  "voucher.placeholder": "券码",
  "voucher.help": "只输入券码；提交后由在线支付服务查询并锁定。",
  "cancel.title": "取消分期",
  "cancel.reasonAccessibility": "取消退款原因",
  "cancel.reasonPlaceholder": "退款取消原因",
  "void.reasonAccessibility": "作废原因",
  "void.reasonPlaceholder": "作废原因",
  "pickup.title": "取货确认",
  "pickup.noteAccessibility": "取货备注",
  "pickup.notePlaceholder": "证件核对或备注",
  "confirmation.cancel": "将按原付款记录执行退款，并在结果明确后取消分期。",
  "confirmation.void": "作废不会退款；仅用于无需退款的错误分期单。",
  "confirmation.pickup": "确认后分期单会标记为已取货。",
  "cart.title": "当前订单",
  "cart.hint":
    "创建时组合根会再次核对购物车 revision，页面快照不能越权替代真实购物车。",
  "cart.empty": "当前购物车为空",
  "create.title": "客户与首付",
  "create.customerNameAccessibility": "客户姓名",
  "create.customerNamePlaceholder": "客户姓名",
  "create.customerPhoneAccessibility": "客户电话",
  "create.customerPhonePlaceholder": "客户电话",
  "create.noteAccessibility": "分期备注",
  "create.notePlaceholder": "备注",
  "create.downPayment": "首付金额",
  "create.downPaymentAccessibility": "首付金额",
  "create.voucherAccessibility": "首付券码",
  "create.minimums": "分期总额最低 {{total}}；首付最低 {{downPayment}}。",
  "draft.count": "{{count}} 项",
  "method.cash": "现金",
  "method.card": "银行卡",
  "method.voucher": "券",
  "status.Active": "进行中",
  "status.PaidOff": "已付清",
  "status.PickedUp": "已取货",
  "status.Cancelled": "已取消",
  "paymentStatus.Recorded": "已记录",
  "paymentStatus.Voided": "已作废",
  "cancellation.RefundCancel": "已退款取消",
  "cancellation.VoidCancel": "已作废",
  "unavailable.title": "分期功能暂不可用",
  "unavailable.subtitle":
    "在线支付恢复、加密缓存或可信收银员运行时尚未接线，请返回销售页。",
  "status.action-failed": "操作失败，请核对状态后重试。",
  "status.authorization-declined": "支付未获批准，分期状态未改变。",
  "status.cancel-complete": "分期已退款取消。",
  "status.conflict": "服务端状态已变化，请刷新后处理。",
  "status.create-complete": "分期已创建并记录首付。",
  "status.details-failed": "详情读取失败。",
  "status.details-unavailable": "本机没有可用详情缓存。",
  "status.history-failed": "分期历史读取失败。",
  "status.invalid-create":
    "请核对购物车、客户、最低 AU$50 总额及最低 AU$20 首付。",
  "status.invalid-repayment": "续付金额或付款信息无效。",
  "status.online-required": "此操作必须在线完成。",
  "status.payment-recovery-required":
    "支付结果未知：恢复完成前禁止再次扣款、退款、作废或切换付款方式。",
  "status.permission-required": "当前收银员没有所需权限。",
  "status.pickup-complete": "取货已确认。",
  "status.repayment-complete": "续付已记录。",
  "status.recovery-complete": "上一笔支付与分期状态已恢复。",
  "status.void-complete": "分期已作废。",
} as const satisfies Record<InstallmentCopyKey, string>;

const installmentCopy = {
  en: installmentEnglishCopy,
  zh: installmentChineseCopy,
} as const;

export type InstallmentLocale = keyof typeof installmentCopy;

export function resolveInstallmentLocale(language?: string): InstallmentLocale {
  return language?.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function installmentText(
  locale: InstallmentLocale,
  key: InstallmentCopyKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  const template = installmentCopy[locale][key];
  if (!values) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name: string) => {
    const value = values[name];
    return value === undefined ? placeholder : String(value);
  });
}
