export const installmentEnglishCopy = {
  eyebrow: "STORE OPERATIONS",
  title: "Installments",
  subtitle: "Installment queries and operations require a live backend.",
  online: "Online",
  offlineShort: "Offline",
  offline:
    "Reconnect to load installments. History, details and operations remain unavailable while offline.",
  "action.recover": "Recover previous action",
  "action.back": "Back",
  "action.history": "History",
  "action.new": "New installment",
  "action.search": "Search",
  "action.refresh": "Refresh",
  "action.refreshing": "Refreshing…",
  "action.reprint": "Reprint",
  "action.reprinting": "Printing…",
  "action.loadMore": "Load more",
  "action.loadingMore": "Loading…",
  "action.retry": "Try again",
  "action.retryDetails": "Retry details",
  "action.goToSales": "Add items in sales",
  "action.continuePayment": "Continue payment",
  "action.more": "More actions",
  "action.closeMore": "Close more actions",
  "action.addRepayment": "Add repayment",
  "action.refundCancel": "Refund & cancel",
  "action.void": "Void",
  "action.confirmPickup": "Confirm pickup",
  "action.confirm": "Confirm",
  "action.create": "Create & take down payment",
  "action.backToSales": "Back to sales",
  "action.working": "Working…",
  "filter.all": "All",
  "filter.active": "Active",
  "filter.paid": "Paid",
  "filter.picked": "Picked",
  "filter.cancelled": "Cancelled",
  "filter.statusLabel": "Status",
  "date.label": "Date",
  "date.all": "All",
  "date.today": "Today",
  "date.last7": "7 days",
  "date.last30": "30 days",
  "date.custom": "Custom",
  "date.from": "From date",
  "date.to": "To date",
  "date.apply": "Apply range",
  "scope.label": "Range",
  "scope.store": "This store",
  "scope.device": "This device",
  "history.title": "Installment history",
  "history.count": "{{count}} items",
  "history.countOne": "1 item",
  "search.accessibility": "Search installments",
  "search.placeholder": "Number, customer, phone",
  "history.loading": "Loading…",
  "history.empty": "No installment records",
  "history.emptyInitial": "No installments have been recorded yet.",
  "history.emptyFiltered": "No installments match these filters.",
  "history.failed": "Installment history could not be loaded.",
  "history.permission": "You do not have permission to view installments.",
  "balance.label": "Balance",
  "details.loading": "Loading details…",
  "details.empty": "Select an installment",
  "details.failed": "Installment details could not be loaded.",
  "details.offlineHint":
    "Details are unavailable. Refresh the selected installment and try again.",
  "reprint.accessibility": "Reprint receipt for {{installmentNumber}}",
  "reprint.hint":
    "Prints another copy of the existing installment receipt.",
  "reprint.succeeded": "Receipt reprinted.",
  "reprint.failed":
    "Receipt could not be reprinted. Check the printer and try again.",
  "metric.total": "Total",
  "metric.down": "Down payment",
  "metric.paid": "Paid",
  "metric.balance": "Balance",
  "section.items": "Items",
  "section.payments": "Payment history",
  "section.note": "Note",
  "section.overview": "Order details",
  "section.pickup": "Pickup",
  "section.cancellation": "Cancellation",
  "field.created": "Created",
  "field.cashier": "Cashier",
  "field.device": "Device",
  "field.minimumDownPayment": "Minimum down payment",
  "field.productCode": "Product",
  "field.lookupCode": "Lookup",
  "field.referenceCode": "Reference",
  "field.itemNumber": "Item number",
  "field.unitPrice": "Original",
  "field.discount": "Discount",
  "field.actual": "Paid",
  "field.paymentMethod": "Method",
  "field.paymentStatus": "Status",
  "field.paymentTime": "Time",
  "field.cashierId": "Cashier ID",
  "field.card": "Card",
  "field.pickupBy": "Picked up by",
  "field.pickupTime": "Pickup time",
  "field.pickupNote": "Pickup note",
  "field.cancelledBy": "Cancelled by",
  "field.cancelledTime": "Cancellation time",
  "field.cancelReason": "Reason",
  "payments.empty": "No recorded payments",
  "completed.picked": "Picked up",
  "completed.cancelled": "Cancelled",
  "repayment.title": "Add repayment",
  "repayment.amountAccessibility": "Repayment amount",
  "repayment.voucherAccessibility": "Repayment voucher code",
  "voucher.placeholder": "Voucher code",
  "voucher.help":
    "Enter the voucher code only; the online payment provider will query and lock it after submission.",
  "cancel.title": "Cancel installment",
  "cancel.reasonAccessibility": "Cancellation reason",
  "cancel.reasonPlaceholder": "Refund-cancel reason",
  "void.reasonAccessibility": "Void reason",
  "void.reasonPlaceholder": "Void reason",
  "pickup.title": "Confirm pickup",
  "pickup.noteAccessibility": "Pickup note",
  "pickup.notePlaceholder": "ID check or note",
  "confirmation.cancel":
    "The original payments will be refunded, then the installment will be cancelled after the result is known.",
  "confirmation.void":
    "Voiding does not refund; use it only for an incorrect installment that needs no refund.",
  "confirmation.pickup":
    "The installment will be marked as picked up after confirmation.",
  "blocked.offline": "Reconnect before continuing this installment operation.",
  "blocked.permission": "The current cashier does not have permission for this action.",
  "blocked.busy": "Another installment operation is still running.",
  "blocked.recovery": "Recover the unknown payment outcome before another action.",
  "blocked.unavailable": "The secure payment route is unavailable. Refresh and try again.",
  "navigation.failed": "Payment could not be prepared. Nothing was charged; check the cart or installment and try again.",
  "cart.title": "Current cart",
  "cart.hint":
    "The composition root checks the cart revision again when creating. This screen snapshot cannot replace the live cart.",
  "cart.empty": "Current cart is empty",
  "create.title": "Customer & down payment",
  "create.customerNameAccessibility": "Customer name",
  "create.customerNamePlaceholder": "Customer name",
  "create.customerPhoneAccessibility": "Customer phone",
  "create.customerPhonePlaceholder": "Customer phone",
  "create.noteAccessibility": "Installment note",
  "create.notePlaceholder": "Note",
  "create.downPayment": "Down payment",
  "create.downPaymentAccessibility": "Down payment amount",
  "create.voucherAccessibility": "Down payment voucher code",
  "create.minimums":
    "Minimum installment total {{total}}; minimum down payment {{downPayment}}.",
  "draft.count": "{{count}} items",
  "method.cash": "Cash",
  "method.card": "Card",
  "method.voucher": "Voucher",
  "status.Active": "Active",
  "status.PaidOff": "Paid off",
  "status.PickedUp": "Picked up",
  "status.Cancelled": "Cancelled",
  "paymentStatus.Recorded": "Recorded",
  "paymentStatus.Voided": "Voided",
  "cancellation.RefundCancel": "Refunded and cancelled",
  "cancellation.VoidCancel": "Voided",
  "unavailable.title": "Installments unavailable",
  "unavailable.subtitle":
    "The trusted payment or cashier runtime is not configured.",
  "status.action-failed": "Operation failed. Check the state and try again.",
  "status.authorization-declined":
    "Payment was declined; no installment change was made.",
  "status.cancel-complete": "Installment refunded and cancelled.",
  "status.conflict": "Server state changed; refresh first.",
  "status.create-complete": "Installment and down payment recorded.",
  "status.details-failed": "Unable to load details.",
  "status.details-unavailable": "Installment details are unavailable.",
  "status.history-failed": "Unable to load history.",
  "status.invalid-create":
    "Check the cart, customer, minimum AUD 50 total and minimum AUD 20 down payment.",
  "status.invalid-repayment": "Repayment amount or tender is invalid.",
  "status.invalid-date-filter": "Choose a valid date range, with the start on or before the end.",
  "status.online-required": "This operation requires a live backend.",
  "status.payment-recovery-required":
    "Payment outcome unknown; recovery is required before any new action.",
  "status.permission-required": "Cashier permission is required.",
  "status.service-unavailable": "The installment service is unavailable. Try again shortly.",
  "status.pickup-complete": "Pickup confirmed.",
  "status.repayment-complete": "Repayment recorded.",
  "status.recovery-complete":
    "Previous payment and installment action recovered.",
  "status.void-complete": "Installment voided.",
} as const;

export type InstallmentCopyKey = keyof typeof installmentEnglishCopy;

const installmentChineseCopy = {
  eyebrow: "门店运营",
  title: "分期",
  subtitle: "分期查询和所有操作都必须连接在线服务。",
  online: "在线",
  offlineShort: "离线",
  offline: "请恢复连接后加载分期；离线时不展示历史、详情，也不能执行任何操作。",
  "action.recover": "恢复上一笔",
  "action.back": "返回",
  "action.history": "历史",
  "action.new": "新建分期",
  "action.search": "查询",
  "action.refresh": "刷新",
  "action.refreshing": "刷新中…",
  "action.reprint": "重打小票",
  "action.reprinting": "打印中…",
  "action.loadMore": "加载更多",
  "action.loadingMore": "加载中…",
  "action.retry": "重试",
  "action.retryDetails": "重试详情",
  "action.goToSales": "去销售添加商品",
  "action.continuePayment": "继续付款",
  "action.more": "更多操作",
  "action.closeMore": "收起更多操作",
  "action.addRepayment": "记录续付",
  "action.refundCancel": "退款并取消",
  "action.void": "作废",
  "action.confirmPickup": "确认已取货",
  "action.confirm": "确认",
  "action.create": "创建分期并收取首付",
  "action.backToSales": "返回销售",
  "action.working": "处理中…",
  "filter.all": "全部",
  "filter.active": "进行中",
  "filter.paid": "已付清",
  "filter.picked": "已取货",
  "filter.cancelled": "已取消",
  "filter.statusLabel": "状态",
  "date.label": "日期",
  "date.all": "全部",
  "date.today": "今天",
  "date.last7": "7 天",
  "date.last30": "30 天",
  "date.custom": "自定义",
  "date.from": "开始日期",
  "date.to": "结束日期",
  "date.apply": "应用日期范围",
  "scope.label": "范围",
  "scope.store": "本店",
  "scope.device": "本机",
  "history.title": "分期历史",
  "history.count": "{{count}} 项",
  "history.countOne": "1 项",
  "search.accessibility": "搜索分期",
  "search.placeholder": "分期号、客户、电话",
  "history.loading": "正在读取…",
  "history.empty": "暂无分期记录",
  "history.emptyInitial": "尚未记录任何分期单。",
  "history.emptyFiltered": "当前筛选条件没有匹配的分期单。",
  "history.failed": "分期历史读取失败。",
  "history.permission": "当前收银员没有查看分期的权限。",
  "balance.label": "余额",
  "details.loading": "正在读取详情…",
  "details.empty": "选择一张分期单",
  "details.failed": "分期详情读取失败。",
  "details.offlineHint": "详情暂不可用，请刷新所选分期后重试。",
  "reprint.accessibility": "重打分期单 {{installmentNumber}} 的小票",
  "reprint.hint": "再次打印这张分期单的既有小票。",
  "reprint.succeeded": "小票已重打。",
  "reprint.failed": "小票重打失败，请检查打印机后重试。",
  "metric.total": "总额",
  "metric.down": "首付",
  "metric.paid": "已付",
  "metric.balance": "余额",
  "section.items": "商品",
  "section.payments": "付款历史",
  "section.note": "备注",
  "section.overview": "分期信息",
  "section.pickup": "取货信息",
  "section.cancellation": "取消信息",
  "field.created": "创建时间",
  "field.cashier": "收银员",
  "field.device": "设备",
  "field.minimumDownPayment": "最低首付",
  "field.productCode": "商品编码",
  "field.lookupCode": "查询码",
  "field.referenceCode": "参考码",
  "field.itemNumber": "货号",
  "field.unitPrice": "原价",
  "field.discount": "折扣",
  "field.actual": "实付",
  "field.paymentMethod": "付款方式",
  "field.paymentStatus": "付款状态",
  "field.paymentTime": "付款时间",
  "field.cashierId": "收银员 ID",
  "field.card": "银行卡",
  "field.pickupBy": "取货确认人",
  "field.pickupTime": "取货时间",
  "field.pickupNote": "取货备注",
  "field.cancelledBy": "取消人",
  "field.cancelledTime": "取消时间",
  "field.cancelReason": "原因",
  "payments.empty": "暂无付款",
  "completed.picked": "已取货",
  "completed.cancelled": "已取消",
  "repayment.title": "续付",
  "repayment.amountAccessibility": "续付金额",
  "repayment.voucherAccessibility": "续付券码",
  "voucher.placeholder": "券码",
  "voucher.help": "只输入券码；提交后由在线支付服务查询并锁定。",
  "cancel.title": "取消分期",
  "cancel.reasonAccessibility": "取消退款原因",
  "cancel.reasonPlaceholder": "退款取消原因",
  "void.reasonAccessibility": "作废原因",
  "void.reasonPlaceholder": "作废原因",
  "pickup.title": "取货确认",
  "pickup.noteAccessibility": "取货备注",
  "pickup.notePlaceholder": "证件核对或备注",
  "confirmation.cancel": "将按原付款记录执行退款，并在结果明确后取消分期。",
  "confirmation.void": "作废不会退款；仅用于无需退款的错误分期单。",
  "confirmation.pickup": "确认后分期单会标记为已取货。",
  "blocked.offline": "请恢复联网后再执行此分期操作。",
  "blocked.permission": "当前收银员没有执行此操作的权限。",
  "blocked.busy": "另一项分期操作仍在处理中。",
  "blocked.recovery": "支付结果未知，请先完成恢复。",
  "blocked.unavailable": "安全支付入口暂不可用，请刷新后重试。",
  "navigation.failed": "支付准备失败，未发生扣款；请核对购物车或分期状态后重试。",
  "cart.title": "当前订单",
  "cart.hint":
    "创建时组合根会再次核对购物车 revision，页面快照不能越权替代真实购物车。",
  "cart.empty": "当前购物车为空",
  "create.title": "客户与首付",
  "create.customerNameAccessibility": "客户姓名",
  "create.customerNamePlaceholder": "客户姓名",
  "create.customerPhoneAccessibility": "客户电话",
  "create.customerPhonePlaceholder": "客户电话",
  "create.noteAccessibility": "分期备注",
  "create.notePlaceholder": "备注",
  "create.downPayment": "首付金额",
  "create.downPaymentAccessibility": "首付金额",
  "create.voucherAccessibility": "首付券码",
  "create.minimums": "分期总额最低 {{total}}；首付最低 {{downPayment}}。",
  "draft.count": "{{count}} 项",
  "method.cash": "现金",
  "method.card": "银行卡",
  "method.voucher": "券",
  "status.Active": "进行中",
  "status.PaidOff": "已付清",
  "status.PickedUp": "已取货",
  "status.Cancelled": "已取消",
  "paymentStatus.Recorded": "已记录",
  "paymentStatus.Voided": "已作废",
  "cancellation.RefundCancel": "已退款取消",
  "cancellation.VoidCancel": "已作废",
  "unavailable.title": "分期功能暂不可用",
  "unavailable.subtitle":
    "在线支付恢复或可信收银员运行时尚未接线，请返回销售页。",
  "status.action-failed": "操作失败，请核对状态后重试。",
  "status.authorization-declined": "支付未获批准，分期状态未改变。",
  "status.cancel-complete": "分期已退款取消。",
  "status.conflict": "服务端状态已变化，请刷新后处理。",
  "status.create-complete": "分期已创建并记录首付。",
  "status.details-failed": "详情读取失败。",
  "status.details-unavailable": "分期详情暂不可用。",
  "status.history-failed": "分期历史读取失败。",
  "status.invalid-create":
    "请核对购物车、客户、最低 AU$50 总额及最低 AU$20 首付。",
  "status.invalid-repayment": "续付金额或付款信息无效。",
  "status.invalid-date-filter": "请选择有效日期范围，开始日期不得晚于结束日期。",
  "status.online-required": "此操作必须在线完成。",
  "status.payment-recovery-required":
    "支付结果未知：恢复完成前禁止再次扣款、退款、作废或切换付款方式。",
  "status.permission-required": "当前收银员没有所需权限。",
  "status.service-unavailable": "分期服务暂不可用，请稍后重试。",
  "status.pickup-complete": "取货已确认。",
  "status.repayment-complete": "续付已记录。",
  "status.recovery-complete": "上一笔支付与分期状态已恢复。",
  "status.void-complete": "分期已作废。",
} as const satisfies Record<InstallmentCopyKey, string>;

const installmentCopy = {
  en: installmentEnglishCopy,
  zh: installmentChineseCopy,
} as const;

export type InstallmentLocale = keyof typeof installmentCopy;

export function resolveInstallmentLocale(language?: string): InstallmentLocale {
  return language?.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function installmentText(
  locale: InstallmentLocale,
  key: InstallmentCopyKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  const template = installmentCopy[locale][key];
  if (!values) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name: string) => {
    const value = values[name];
    return value === undefined ? placeholder : String(value);
  });
}
